# Generated by Django 5.1.15 on 2026-06-06 17:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0002_initial'),
        ('organizations', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeExit',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('clearance_in_progress', 'Clearance In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=30)),
                ('resignation_date', models.DateField(blank=True, null=True)),
                ('notice_start_date', models.DateField(blank=True, null=True)),
                ('notice_end_date', models.DateField(blank=True, null=True)),
                ('proposed_last_working_date', models.DateField(blank=True, null=True)),
                ('approved_last_working_date', models.DateField(blank=True, null=True)),
                ('actual_exit_date', models.DateField(blank=True, null=True)),
                ('exit_reason', models.CharField(blank=True, max_length=120)),
                ('exit_reason_detail', models.TextField(blank=True)),
                ('is_regrettable', models.BooleanField(default=False)),
                ('rehire_eligible', models.BooleanField(default=True)),
                ('workflow_reference', models.CharField(blank=True, max_length=120)),
                ('clearance_status_snapshot', models.JSONField(blank=True, default=dict)),
                ('handover_notes', models.TextField(blank=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exit_record', to='employees.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_exits', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Employee Exit',
                'verbose_name_plural': 'Employee Exits',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeLifecycleEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('onboarding', 'Onboarding'), ('probation', 'Probation'), ('confirmation', 'Confirmation'), ('transfer', 'Transfer'), ('promotion', 'Promotion'), ('designation_change', 'Designation Change'), ('reporting_change', 'Reporting Change'), ('employment_type_change', 'Employment Type Change'), ('exit', 'Exit'), ('rehire', 'Rehire'), ('other', 'Other')], max_length=40)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('initiated_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('workflow_reference', models.CharField(blank=True, max_length=120)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lifecycle_events', to='employees.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lifecycle_events', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Employee Lifecycle Event',
                'verbose_name_plural': 'Employee Lifecycle Events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeMovement',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('movement_type', models.CharField(choices=[('transfer', 'Transfer'), ('promotion', 'Promotion'), ('designation_change', 'Designation Change'), ('reporting_change', 'Reporting Change'), ('grade_change', 'Grade Change'), ('employment_type_change', 'Employment Type Change'), ('location_change', 'Location Change'), ('other', 'Other')], max_length=30)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('effective_date', models.DateField()),
                ('reason', models.TextField(blank=True)),
                ('workflow_reference', models.CharField(blank=True, max_length=120)),
                ('current_snapshot', models.JSONField(blank=True, default=dict)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='employees.employee')),
                ('from_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movement_from_branches', to='organizations.branch')),
                ('from_business_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movement_from_business_units', to='organizations.businessunit')),
                ('from_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movement_from_departments', to='organizations.department')),
                ('from_designation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movement_from_designations', to='organizations.designation')),
                ('from_employment_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movement_from_employment_types', to='organizations.employmenttype')),
                ('from_grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movement_from_grades', to='organizations.grade')),
                ('from_legal_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movement_from_legal_entities', to='organizations.legalentity')),
                ('from_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movement_from_locations', to='organizations.location')),
                ('from_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movement_from_manager_set', to='employees.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_movements', to='tenants.tenant')),
                ('to_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movement_to_branches', to='organizations.branch')),
                ('to_business_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movement_to_business_units', to='organizations.businessunit')),
                ('to_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movement_to_departments', to='organizations.department')),
                ('to_designation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movement_to_designations', to='organizations.designation')),
                ('to_employment_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movement_to_employment_types', to='organizations.employmenttype')),
                ('to_grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movement_to_grades', to='organizations.grade')),
                ('to_legal_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movement_to_legal_entities', to='organizations.legalentity')),
                ('to_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movement_to_locations', to='organizations.location')),
                ('to_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movement_to_manager_set', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Employee Movement',
                'verbose_name_plural': 'Employee Movements',
                'ordering': ['-effective_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeOnboarding',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('blocked', 'Blocked'), ('cancelled', 'Cancelled')], default='not_started', max_length=20)),
                ('expected_joining_date', models.DateField(blank=True, null=True)),
                ('actual_joining_date', models.DateField(blank=True, null=True)),
                ('onboarding_template_code', models.CharField(blank=True, max_length=80)),
                ('preboarding_started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_owner_identifier', models.CharField(blank=True, max_length=120)),
                ('workflow_reference', models.CharField(blank=True, max_length=120)),
                ('checklist_snapshot', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_record', to='employees.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_onboardings', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Employee Onboarding',
                'verbose_name_plural': 'Employee Onboardings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProbationReview',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('review_date', models.DateField()),
                ('probation_end_date', models.DateField(blank=True, null=True)),
                ('decision', models.CharField(choices=[('pending', 'Pending'), ('confirm', 'Confirm'), ('extend', 'Extend'), ('separate', 'Separate')], default='pending', max_length=20)),
                ('extension_end_date', models.DateField(blank=True, null=True)),
                ('reviewer_identifier', models.CharField(blank=True, max_length=120)),
                ('workflow_reference', models.CharField(blank=True, max_length=120)),
                ('remarks', models.TextField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='probation_reviews', to='employees.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='probation_reviews', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Probation Review',
                'verbose_name_plural': 'Probation Reviews',
                'ordering': ['-review_date', '-created_at'],
            },
        ),
    ]
