# Generated by Django 5.1.15 on 2026-06-06 17:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('iam', '0001_initial'),
        ('organizations', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowInstance',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('module', models.CharField(choices=[('employees', 'Employees'), ('lifecycle', 'Lifecycle'), ('leave', 'Leave'), ('attendance', 'Attendance'), ('documents', 'Documents'), ('config', 'Configuration'), ('payroll', 'Payroll'), ('other', 'Other')], max_length=30)),
                ('trigger_key', models.CharField(max_length=120)),
                ('subject_type', models.CharField(max_length=120)),
                ('subject_identifier', models.CharField(max_length=120)),
                ('employee_identifier', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('in_progress', 'In Progress'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('current_step_order', models.PositiveIntegerField(default=0)),
                ('initiated_by_identifier', models.CharField(blank=True, max_length=120)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('payload_snapshot', models.JSONField(blank=True, default=dict)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_instances', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Workflow Instance',
                'verbose_name_plural': 'Workflow Instances',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowStep',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step_order', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('mode', models.CharField(choices=[('sequential', 'Sequential'), ('parallel', 'Parallel')], default='sequential', max_length=20)),
                ('actor_type', models.CharField(choices=[('role', 'Role'), ('membership', 'Membership'), ('manager', 'Manager'), ('hr_owner', 'HR Owner'), ('configured_user', 'Configured User')], default='role', max_length=20)),
                ('permission_key', models.CharField(blank=True, max_length=120)),
                ('scope_type', models.CharField(blank=True, choices=[('self', 'Self'), ('direct_reports', 'Direct Reports'), ('indirect_reports', 'Indirect Reports'), ('department', 'Department'), ('branch', 'Branch'), ('legal_entity', 'Legal Entity'), ('business_unit', 'Business Unit'), ('grade', 'Grade'), ('explicit_assignment', 'Explicit Assignment'), ('tenant_all', 'Tenant Wide')], max_length=40)),
                ('auto_approve_after_hours', models.PositiveIntegerField(default=0)),
                ('escalate_after_hours', models.PositiveIntegerField(default=0)),
                ('allow_delegate', models.BooleanField(default=True)),
                ('allow_send_back', models.BooleanField(default=True)),
                ('allow_comment', models.BooleanField(default=True)),
                ('rule_snapshot', models.JSONField(blank=True, default=dict)),
                ('membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_steps', to='iam.tenantmembership')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_steps', to='iam.role')),
            ],
            options={
                'verbose_name': 'Workflow Step',
                'verbose_name_plural': 'Workflow Steps',
                'ordering': ['template', 'step_order'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowStepInstance',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step_order', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('mode', models.CharField(choices=[('sequential', 'Sequential'), ('parallel', 'Parallel')], default='sequential', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('in_progress', 'In Progress'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_action', models.CharField(blank=True, choices=[('submit', 'Submit'), ('approve', 'Approve'), ('reject', 'Reject'), ('send_back', 'Send Back'), ('escalate', 'Escalate'), ('delegate', 'Delegate'), ('cancel', 'Cancel'), ('comment', 'Comment')], max_length=20)),
                ('resolution_comment', models.TextField(blank=True)),
                ('template_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='step_instances', to='workflows.workflowstep')),
                ('workflow_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_instances', to='workflows.workflowinstance')),
            ],
            options={
                'verbose_name': 'Workflow Step Instance',
                'verbose_name_plural': 'Workflow Step Instances',
                'ordering': ['workflow_instance', 'step_order'],
                'unique_together': {('workflow_instance', 'step_order')},
            },
        ),
        migrations.CreateModel(
            name='WorkflowAssignment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_type', models.CharField(choices=[('role', 'Role'), ('membership', 'Membership'), ('manager', 'Manager'), ('hr_owner', 'HR Owner'), ('configured_user', 'Configured User')], max_length=20)),
                ('actor_identifier', models.CharField(blank=True, max_length=120)),
                ('is_delegated', models.BooleanField(default=False)),
                ('delegated_from_identifier', models.CharField(blank=True, max_length=120)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_assignments', to='iam.tenantmembership')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_assignments', to='iam.role')),
                ('step_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='workflows.workflowstepinstance')),
            ],
            options={
                'verbose_name': 'Workflow Assignment',
                'verbose_name_plural': 'Workflow Assignments',
                'ordering': ['step_instance', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowActionLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('submit', 'Submit'), ('approve', 'Approve'), ('reject', 'Reject'), ('send_back', 'Send Back'), ('escalate', 'Escalate'), ('delegate', 'Delegate'), ('cancel', 'Cancel'), ('comment', 'Comment')], max_length=20)),
                ('actor_identifier', models.CharField(blank=True, max_length=120)),
                ('comment', models.TextField(blank=True)),
                ('from_status', models.CharField(blank=True, choices=[('draft', 'Draft'), ('pending', 'Pending'), ('in_progress', 'In Progress'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], max_length=20)),
                ('to_status', models.CharField(blank=True, choices=[('draft', 'Draft'), ('pending', 'Pending'), ('in_progress', 'In Progress'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], max_length=20)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('workflow_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to='workflows.workflowinstance')),
                ('step_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_logs', to='workflows.workflowstepinstance')),
            ],
            options={
                'verbose_name': 'Workflow Action Log',
                'verbose_name_plural': 'Workflow Action Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowTemplate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=60)),
                ('name', models.CharField(max_length=255)),
                ('module', models.CharField(choices=[('employees', 'Employees'), ('lifecycle', 'Lifecycle'), ('leave', 'Leave'), ('attendance', 'Attendance'), ('documents', 'Documents'), ('config', 'Configuration'), ('payroll', 'Payroll'), ('other', 'Other')], max_length=30)),
                ('trigger_key', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_system_seeded', models.BooleanField(default=False)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('condition_snapshot', models.JSONField(blank=True, default=dict)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_templates', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Workflow Template',
                'verbose_name_plural': 'Workflow Templates',
                'ordering': ['module', 'name'],
                'unique_together': {('tenant', 'code', 'version')},
            },
        ),
        migrations.AddField(
            model_name='workflowstep',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='workflows.workflowtemplate'),
        ),
        migrations.AddField(
            model_name='workflowinstance',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instances', to='workflows.workflowtemplate'),
        ),
        migrations.CreateModel(
            name='WorkflowTemplateAssignment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('priority', models.PositiveIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_template_assignments', to='organizations.branch')),
                ('business_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_template_assignments', to='organizations.businessunit')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_template_assignments', to='organizations.department')),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_template_assignments', to='organizations.grade')),
                ('legal_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_template_assignments', to='organizations.legalentity')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='workflows.workflowtemplate')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_template_assignments', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Workflow Template Assignment',
                'verbose_name_plural': 'Workflow Template Assignments',
                'ordering': ['priority', 'created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='workflowstep',
            unique_together={('template', 'step_order')},
        ),
    ]
