# Generated by Django 5.1.15 on 2026-09-07 05:25

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0002_tenant_onboarding_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='HrmsLaunchRemediationAssignment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gate_ref', models.CharField(max_length=180)),
                ('module_ref', models.CharField(max_length=120)),
                ('module_label', models.CharField(max_length=160)),
                ('label', models.CharField(max_length=180)),
                ('severity', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('ignored', 'Ignored')], default='open', max_length=20)),
                ('owner_role_ref', models.CharField(max_length=120)),
                ('assigned_to_identifier', models.CharField(blank=True, max_length=160)),
                ('action_href', models.CharField(max_length=240)),
                ('action_label', models.CharField(max_length=160)),
                ('sla_days', models.PositiveSmallIntegerField(default=3)),
                ('current_value', models.CharField(blank=True, max_length=240)),
                ('evidence_ref', models.CharField(blank=True, max_length=180)),
                ('first_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('due_source_ref', models.CharField(default='launch_audit.sla_days', max_length=120)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by_identifier', models.CharField(blank=True, max_length=160)),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('reminder_count', models.PositiveSmallIntegerField(default=0)),
                ('escalated_at', models.DateTimeField(blank=True, null=True)),
                ('escalated_by_identifier', models.CharField(blank=True, max_length=160)),
                ('escalation_owner_role_ref', models.CharField(blank=True, max_length=120)),
                ('ignored_at', models.DateTimeField(blank=True, null=True)),
                ('ignored_by_identifier', models.CharField(blank=True, max_length=160)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True)),
                ('action_history', models.JSONField(blank=True, default=list)),
                ('assignment_snapshot', models.JSONField(blank=True, default=dict)),
                ('source_hash', models.CharField(blank=True, max_length=64)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hrms_launch_remediation_assignments', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'HRMS Launch Remediation Assignment',
                'verbose_name_plural': 'HRMS Launch Remediation Assignments',
                'ordering': ['status', 'severity', 'module_ref', 'gate_ref'],
                'indexes': [models.Index(fields=['tenant', 'status', 'severity'], name='common_hrms_tenant__ea6340_idx'), models.Index(fields=['tenant', 'module_ref'], name='common_hrms_tenant__bdea8a_idx'), models.Index(fields=['tenant', 'owner_role_ref'], name='common_hrms_tenant__52516a_idx')],
                'unique_together': {('tenant', 'gate_ref')},
            },
        ),
    ]
