# Generated by Django 5.1.15 on 2026-09-07 06:37

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('tenants', '0002_tenant_onboarding_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaasCommercialAuditEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=80)),
                ('actor_identifier', models.CharField(blank=True, max_length=160)),
                ('source_ref', models.CharField(default='saas.commercial_control.lifecycle.v1', max_length=160)),
                ('profile_ref', models.CharField(max_length=160)),
                ('profile_source', models.CharField(max_length=80)),
                ('plan_ref', models.CharField(max_length=80)),
                ('subscription_status', models.CharField(max_length=40)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('previous_state', models.JSONField(blank=True, default=dict)),
                ('new_state', models.JSONField(blank=True, default=dict)),
                ('usage_snapshot', models.JSONField(blank=True, default=list)),
                ('enforcement_snapshot', models.JSONField(blank=True, default=dict)),
                ('event_snapshot', models.JSONField(blank=True, default=dict)),
                ('source_hash', models.CharField(blank=True, max_length=64)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saas_commercial_audit_events', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'SaaS Commercial Audit Event',
                'verbose_name_plural': 'SaaS Commercial Audit Events',
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['tenant', 'event_type', '-occurred_at'], name='common_saas_tenant__d7f231_idx'), models.Index(fields=['tenant', 'plan_ref'], name='common_saas_tenant__cfe0b6_idx')],
            },
        ),
        migrations.CreateModel(
            name='SaasUsageMeterSnapshot',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('profile_ref', models.CharField(max_length=160)),
                ('profile_source', models.CharField(max_length=80)),
                ('plan_ref', models.CharField(max_length=80)),
                ('subscription_status', models.CharField(max_length=40)),
                ('meter_ref', models.CharField(max_length=120)),
                ('label', models.CharField(max_length=160)),
                ('current_value', models.PositiveIntegerField(default=0)),
                ('limit_value', models.PositiveIntegerField(default=0)),
                ('remaining_value', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(max_length=40)),
                ('source_ref', models.CharField(default='saas.commercial_control.snapshot.v1', max_length=160)),
                ('actor_identifier', models.CharField(blank=True, max_length=160)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('evidence_snapshot', models.JSONField(blank=True, default=dict)),
                ('source_hash', models.CharField(blank=True, max_length=64)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saas_usage_meter_snapshots', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'SaaS Usage Meter Snapshot',
                'verbose_name_plural': 'SaaS Usage Meter Snapshots',
                'ordering': ['-recorded_at', 'meter_ref'],
                'indexes': [models.Index(fields=['tenant', 'meter_ref', '-recorded_at'], name='common_saas_tenant__76a91d_idx'), models.Index(fields=['tenant', 'status'], name='common_saas_tenant__ad36a7_idx')],
            },
        ),
    ]
