# Generated by Django 5.1.15 on 2026-09-07 07:20

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_saascommercialauditevent_saasusagemetersnapshot'),
        ('tenants', '0002_tenant_onboarding_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaasTenantChangeRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_type', models.CharField(choices=[('plan_change', 'Plan Change'), ('billing_contact', 'Billing Contact'), ('configuration_change', 'Configuration Change')], max_length=40)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('applied', 'Applied'), ('canceled', 'Canceled')], default='submitted', max_length=30)),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('target_ref', models.CharField(blank=True, max_length=180)),
                ('requested_by_identifier', models.CharField(max_length=160)),
                ('decided_by_identifier', models.CharField(blank=True, max_length=160)),
                ('applied_by_identifier', models.CharField(blank=True, max_length=160)),
                ('requested_payload', models.JSONField(blank=True, default=dict)),
                ('current_snapshot', models.JSONField(blank=True, default=dict)),
                ('decision_note', models.TextField(blank=True)),
                ('action_history', models.JSONField(blank=True, default=list)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('source_ref', models.CharField(default='saas.tenant_admin.change_request.v1', max_length=160)),
                ('source_hash', models.CharField(blank=True, max_length=64)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saas_tenant_change_requests', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'SaaS Tenant Change Request',
                'verbose_name_plural': 'SaaS Tenant Change Requests',
                'ordering': ['-requested_at', '-updated_at'],
                'indexes': [models.Index(fields=['tenant', 'request_type', 'status'], name='common_saas_tenant__18affb_idx'), models.Index(fields=['tenant', 'status', '-requested_at'], name='common_saas_tenant__7a3404_idx'), models.Index(fields=['tenant', 'target_ref'], name='common_saas_tenant__f955aa_idx')],
            },
        ),
    ]
