# Generated by Django 5.1.15 on 2026-09-07 07:33

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_saas_tenant_change_request'),
        ('tenants', '0002_tenant_onboarding_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaasSupportAccessGrant',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('active', 'Active'), ('ended', 'Ended'), ('revoked', 'Revoked'), ('expired', 'Expired')], default='requested', max_length=30)),
                ('support_agent_identifier', models.CharField(max_length=160)),
                ('reason', models.TextField()),
                ('scope_refs', models.JSONField(blank=True, default=list)),
                ('requested_duration_minutes', models.PositiveSmallIntegerField(default=60)),
                ('approved_duration_minutes', models.PositiveSmallIntegerField(default=0)),
                ('requested_by_identifier', models.CharField(max_length=160)),
                ('approved_by_identifier', models.CharField(blank=True, max_length=160)),
                ('revoked_by_identifier', models.CharField(blank=True, max_length=160)),
                ('started_by_identifier', models.CharField(blank=True, max_length=160)),
                ('ended_by_identifier', models.CharField(blank=True, max_length=160)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('access_starts_at', models.DateTimeField(blank=True, null=True)),
                ('access_expires_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True)),
                ('session_ref', models.CharField(blank=True, max_length=180)),
                ('action_history', models.JSONField(blank=True, default=list)),
                ('request_snapshot', models.JSONField(blank=True, default=dict)),
                ('source_ref', models.CharField(default='saas.support_access.grant.v1', max_length=160)),
                ('source_hash', models.CharField(blank=True, max_length=64)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saas_support_access_grants', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'SaaS Support Access Grant',
                'verbose_name_plural': 'SaaS Support Access Grants',
                'ordering': ['-requested_at', '-updated_at'],
                'indexes': [models.Index(fields=['tenant', 'status', '-requested_at'], name='common_saas_tenant__0da123_idx'), models.Index(fields=['tenant', 'support_agent_identifier'], name='common_saas_tenant__818685_idx'), models.Index(fields=['tenant', 'access_expires_at'], name='common_saas_tenant__6f45d2_idx')],
            },
        ),
    ]
