# Generated by Django 5.1.15 on 2026-09-07 09:21

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_saas_support_access_grant'),
        ('tenants', '0002_tenant_onboarding_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaasIncidentRecord',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('incident_ref', models.CharField(max_length=160)),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=30)),
                ('status', models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged'), ('mitigated', 'Mitigated'), ('resolved', 'Resolved'), ('canceled', 'Canceled')], default='open', max_length=30)),
                ('impact_refs', models.JSONField(blank=True, default=list)),
                ('owner_role_ref', models.CharField(default='platform-owner', max_length=120)),
                ('detected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('mitigated_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('target_response_minutes', models.PositiveIntegerField(default=60)),
                ('target_resolution_minutes', models.PositiveIntegerField(default=240)),
                ('breached_response_at', models.DateTimeField(blank=True, null=True)),
                ('breached_resolution_at', models.DateTimeField(blank=True, null=True)),
                ('action_history', models.JSONField(blank=True, default=list)),
                ('incident_snapshot', models.JSONField(blank=True, default=dict)),
                ('source_ref', models.CharField(default='saas.incident.record.v1', max_length=160)),
                ('source_hash', models.CharField(blank=True, max_length=64)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saas_incident_records', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'SaaS Incident Record',
                'verbose_name_plural': 'SaaS Incident Records',
                'ordering': ['status', '-detected_at'],
                'indexes': [models.Index(fields=['tenant', 'status', 'severity'], name='common_saas_tenant__fca114_idx'), models.Index(fields=['tenant', '-detected_at'], name='common_saas_tenant__ca12db_idx'), models.Index(fields=['tenant', 'owner_role_ref'], name='common_saas_tenant__7c4ef8_idx')],
                'unique_together': {('tenant', 'incident_ref')},
            },
        ),
    ]
