# Generated by Django 5.1.15 on 2026-09-14 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_hrmsimportbatchaudit'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='hrmsimportbatchaudit',
            new_name='common_hrms_tenant__c40ff2_idx',
            old_name='common_hrms_tenant__23363d_idx',
        ),
        migrations.RenameIndex(
            model_name='hrmsimportbatchaudit',
            new_name='common_hrms_tenant__357800_idx',
            old_name='common_hrms_tenant__217dd7_idx',
        ),
        migrations.RenameIndex(
            model_name='hrmsimportbatchaudit',
            new_name='common_hrms_tenant__3dd23f_idx',
            old_name='common_hrms_tenant__5c9a48_idx',
        ),
    ]
