# Generated by Django 5.1.15 on 2026-06-19 15:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        ('tenants', '0002_tenant_onboarding_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationChannelConfiguration',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('in_app', 'In-App'), ('email', 'Email'), ('sms', 'SMS'), ('push', 'Push'), ('whatsapp', 'WhatsApp')], max_length=20)),
                ('is_enabled', models.BooleanField(default=True)),
                ('backend_key', models.CharField(choices=[('in_app_default', 'In-App Default'), ('email_smtp', 'Email SMTP'), ('console', 'Console'), ('sms_console', 'SMS Console'), ('push_console', 'Push Console'), ('whatsapp_console', 'WhatsApp Console')], max_length=60)),
                ('sender_identifier', models.CharField(blank=True, max_length=120)),
                ('sender_address', models.CharField(blank=True, max_length=255)),
                ('provider_config', models.JSONField(blank=True, default=dict)),
                ('delivery_policy', models.JSONField(blank=True, default=dict)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_channel_configurations', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Notification Channel Configuration',
                'verbose_name_plural': 'Notification Channel Configurations',
                'ordering': ['channel'],
                'unique_together': {('tenant', 'channel')},
            },
        ),
    ]
