export type ReportCategory = "HR Core" | "Attendance" | "Payroll Finance" | "Compliance" | "SaaS Ops";

export type ReportStatus = "Ready" | "Planned" | "Provider gated";

export type ReportCatalogItem = {
  key: string;
  title: string;
  category: ReportCategory;
  primaryPersona: string;
  description: string;
  filters: string[];
  exports: string[];
  status: ReportStatus;
  route?: string;
  exportRoute?: string;
};

export const reportCatalog: ReportCatalogItem[] = [
  {
    key: "workforce",
    title: "Employee master report",
    category: "HR Core",
    primaryPersona: "HR Admin",
    description: "Employee structure, status, manager coverage, and workforce hygiene.",
    filters: ["Legal entity", "Branch", "Department", "Manager", "Status"],
    exports: ["CSV"],
    status: "Ready",
    route: "/hr-admin/reports/workforce",
    exportRoute: "/api/hr-admin/reports/workforce",
  },
  {
    key: "document-compliance",
    title: "Document compliance report",
    category: "HR Core",
    primaryPersona: "HR Admin",
    description: "Verification, rejection, mandatory rule, and expiry risk coverage.",
    filters: ["Document category", "Verification status", "Expiry window", "Department"],
    exports: ["CSV"],
    status: "Ready",
    route: "/hr-admin/reports/document-compliance",
    exportRoute: "/api/hr-admin/reports/document-compliance",
  },
  {
    key: "lifecycle-queue",
    title: "Lifecycle queue report",
    category: "HR Core",
    primaryPersona: "HR Admin",
    description: "Onboarding, probation, movement, exit, and workflow backlog.",
    filters: ["Lifecycle type", "Owner", "Status", "Due date"],
    exports: ["CSV"],
    status: "Ready",
    route: "/hr-admin/reports/lifecycle-queue",
    exportRoute: "/api/hr-admin/reports/lifecycle-queue",
  },
  {
    key: "lifecycle-aging",
    title: "Lifecycle aging and SLA report",
    category: "HR Core",
    primaryPersona: "HR Admin",
    description: "Lifecycle age buckets, overdue owners, escalation dates, and SLA risk.",
    filters: ["Lifecycle type", "Owner", "Age bucket", "SLA risk", "Escalation"],
    exports: ["CSV"],
    status: "Ready",
    route: "/hr-admin/reports/lifecycle-aging",
    exportRoute: "/api/hr-admin/reports/lifecycle-aging",
  },
  {
    key: "attendance-register",
    title: "Daily attendance register",
    category: "Attendance",
    primaryPersona: "HR Admin",
    description: "Daily attendance status, missing punches, and regularization exposure.",
    filters: ["Date range", "Branch", "Shift", "Department", "Status"],
    exports: ["CSV", "XLSX"],
    status: "Ready",
    route: "/hr-admin/reports/attendance-register",
    exportRoute: "/api/hr-admin/reports/attendance-register",
  },
  {
    key: "leave-balance",
    title: "Leave balance report",
    category: "Attendance",
    primaryPersona: "HR Admin",
    description: "Leave balances, utilization, liability, and pending approvals.",
    filters: ["Leave type", "Employee", "Department", "Policy"],
    exports: ["CSV", "XLSX"],
    status: "Ready",
    route: "/hr-admin/reports/leave-balance",
    exportRoute: "/api/hr-admin/reports/leave-balance",
  },
  {
    key: "attendance-exceptions",
    title: "Attendance exceptions SLA report",
    category: "Attendance",
    primaryPersona: "HR Admin",
    description: "Regularization aging, requested corrections, approval SLA, and payroll impact.",
    filters: ["Request status", "Requested status", "Current status", "SLA risk", "Payroll impact"],
    exports: ["CSV"],
    status: "Ready",
    route: "/hr-admin/reports/attendance-exceptions",
    exportRoute: "/api/hr-admin/reports/attendance-exceptions",
  },
  {
    key: "payroll-register",
    title: "Payroll register",
    category: "Payroll Finance",
    primaryPersona: "Payroll Finance Manager",
    description: "Payroll run earnings, deductions, net pay, lock status, and artifact trace.",
    filters: ["Payroll period", "Legal entity", "Department", "Cost center", "Run status"],
    exports: ["CSV", "XLSX"],
    status: "Ready",
    route: "/hr-admin/reports/payroll-register",
    exportRoute: "/api/hr-admin/reports/payroll-register",
  },
  {
    key: "payroll-input-exceptions",
    title: "Payroll input exceptions report",
    category: "Payroll Finance",
    primaryPersona: "Payroll Finance Manager",
    description: "Pre-close payroll input snapshot readiness, blockers, warnings, lock state, and source hash evidence.",
    filters: ["Payroll run", "Snapshot status", "Pay group", "Lock state", "Issue type"],
    exports: ["CSV"],
    status: "Ready",
    route: "/hr-admin/reports/payroll-input-exceptions",
    exportRoute: "/api/hr-admin/reports/payroll-input-exceptions",
  },
  {
    key: "salary-variance",
    title: "Salary variance report",
    category: "Payroll Finance",
    primaryPersona: "Payroll Finance Manager",
    description: "Period-over-period payroll changes, exceptions, and review notes.",
    filters: ["Payroll period", "Variance band", "Department", "Employee"],
    exports: ["CSV", "XLSX"],
    status: "Ready",
    route: "/hr-admin/reports/salary-variance",
    exportRoute: "/api/hr-admin/reports/salary-variance",
  },
  {
    key: "payroll-review-exceptions",
    title: "Payroll review exceptions report",
    category: "Payroll Finance",
    primaryPersona: "Payroll Finance Manager",
    description: "Payroll calculation and review exceptions by severity, status, component, decision, and source snapshot.",
    filters: ["Payroll run", "Severity", "Status", "Category", "Decision state"],
    exports: ["CSV"],
    status: "Ready",
    route: "/hr-admin/reports/payroll-review-exceptions",
    exportRoute: "/api/hr-admin/reports/payroll-review-exceptions",
  },
  {
    key: "payroll-adjustments",
    title: "Payroll adjustments report",
    category: "Payroll Finance",
    primaryPersona: "Payroll Finance Manager",
    description: "One-time payroll adjustments by kind, direction, approval state, effective date, source reference, and hash evidence.",
    filters: ["Payroll run", "Kind", "Direction", "Status", "Approval state"],
    exports: ["CSV"],
    status: "Ready",
    route: "/hr-admin/reports/payroll-adjustments",
    exportRoute: "/api/hr-admin/reports/payroll-adjustments",
  },
  {
    key: "payroll-settlements",
    title: "Payroll settlements report",
    category: "Payroll Finance",
    primaryPersona: "Payroll Finance Manager",
    description: "Full-and-final settlement packages by employee, run, package status, approval state, net settlement, line composition, and source hash.",
    filters: ["Payroll run", "Status", "Approval state", "Net amount risk", "Line kind"],
    exports: ["CSV"],
    status: "Ready",
    route: "/hr-admin/reports/payroll-settlements",
    exportRoute: "/api/hr-admin/reports/payroll-settlements",
  },
  {
    key: "payroll-close-readiness",
    title: "Payroll close readiness report",
    category: "Payroll Finance",
    primaryPersona: "Payroll Finance Manager",
    description: "Run-level close gate combining input locks, review blockers, pending adjustments, settlements, output state, and evidence hashes.",
    filters: ["Payroll run", "Close readiness", "Risk", "Blocker category", "Output state"],
    exports: ["CSV"],
    status: "Ready",
    route: "/hr-admin/reports/payroll-close-readiness",
    exportRoute: "/api/hr-admin/reports/payroll-close-readiness",
  },
  {
    key: "payslip-publication",
    title: "Payslip publication report",
    category: "Payroll Finance",
    primaryPersona: "Payroll Finance Manager",
    description: "Payslip delivery, employee acknowledgement, signed access, download activity, and source-hash evidence.",
    filters: ["Payroll run", "Publication state", "Access risk", "Artifact status", "Acknowledgement"],
    exports: ["CSV"],
    status: "Ready",
    route: "/hr-admin/reports/payslip-publication",
    exportRoute: "/api/hr-admin/reports/payslip-publication",
  },
  {
    key: "bank-advice",
    title: "Bank advice report",
    category: "Payroll Finance",
    primaryPersona: "Payroll Finance Manager",
    description: "Payout-ready employees, bank validation exceptions, and payment handoff state.",
    filters: ["Payroll period", "Bank", "Validation status", "Payment status"],
    exports: ["CSV", "XLSX"],
    status: "Ready",
    route: "/hr-admin/reports/bank-advice",
    exportRoute: "/api/hr-admin/reports/bank-advice",
  },
  {
    key: "finance-handoff-exceptions",
    title: "Finance handoff exceptions report",
    category: "Payroll Finance",
    primaryPersona: "Payroll Finance Manager",
    description: "Failed, queued, retried, transmitted, acknowledged, and audit-pack-ready payroll finance handoff exceptions.",
    filters: ["Handoff status", "Delivery status", "Provider", "Risk", "Blocker category"],
    exports: ["CSV"],
    status: "Ready",
    route: "/hr-admin/reports/finance-handoff-exceptions",
    exportRoute: "/api/hr-admin/reports/finance-handoff-exceptions",
  },
  {
    key: "tds-efile-readiness",
    title: "TDS e-file readiness report",
    category: "Compliance",
    primaryPersona: "Payroll Finance Manager",
    description: "TDS components, Form 24Q calendar, declaration lock, PAN coverage, challan mapping, and provider route readiness.",
    filters: ["Quarter", "Legal entity", "Provider profile", "Readiness status"],
    exports: ["CSV", "PDF"],
    status: "Provider gated",
    route: "/hr-admin/payroll-statutory",
  },
  {
    key: "challan-reconciliation",
    title: "Challan reconciliation report",
    category: "Compliance",
    primaryPersona: "Payroll Finance Manager",
    description: "Statutory filing calendars matched to deduction artifacts, registration evidence, payment readiness, and provider route status.",
    filters: ["Quarter", "Legal entity", "Filing type", "Payment status", "Provider route"],
    exports: ["CSV", "XLSX"],
    status: "Ready",
    route: "/hr-admin/reports/challan-reconciliation",
    exportRoute: "/api/hr-admin/reports/challan-reconciliation",
  },
  {
    key: "statutory-filing-status",
    title: "Statutory filing status report",
    category: "Compliance",
    primaryPersona: "Payroll Finance Manager",
    description: "Filing calendar due dates, open/overdue/acknowledged state, evidence readiness, provider route, and output profile tracking.",
    filters: ["Filing type", "Due status", "Provider route", "Output profile"],
    exports: ["CSV", "XLSX"],
    status: "Ready",
    route: "/hr-admin/reports/statutory-filing-status",
    exportRoute: "/api/hr-admin/reports/statutory-filing-status",
  },
  {
    key: "provider-filing-receipts",
    title: "Provider filing receipts report",
    category: "Compliance",
    primaryPersona: "Payroll Finance Manager",
    description: "Provider submissions, receipt references, acknowledgements, callbacks, retry state, queue jobs, checksum, and failure evidence.",
    filters: ["Provider route", "Delivery status", "Provider status", "Artifact kind"],
    exports: ["CSV", "XLSX"],
    status: "Ready",
    route: "/hr-admin/reports/provider-filing-receipts",
    exportRoute: "/api/hr-admin/reports/provider-filing-receipts",
  },
  {
    key: "statutory-deductions",
    title: "Statutory deduction summary",
    category: "Compliance",
    primaryPersona: "Payroll Finance Manager",
    description: "Configurable statutory deductions by component, jurisdiction, payroll period, and legal entity.",
    filters: ["Payroll period", "Legal entity", "Jurisdiction", "Component"],
    exports: ["CSV", "XLSX"],
    status: "Ready",
    route: "/hr-admin/reports/statutory-deductions",
  },
  {
    key: "tenant-launch-readiness",
    title: "Tenant launch readiness report",
    category: "SaaS Ops",
    primaryPersona: "Platform Admin",
    description: "Launch gates, blockers, warnings, tenant setup coverage, and release actions.",
    filters: ["Tenant", "Plan", "Launch status", "Owner"],
    exports: ["CSV"],
    status: "Ready",
    route: "/platform-admin",
  },
  {
    key: "support-session-audit",
    title: "Support session audit report",
    category: "SaaS Ops",
    primaryPersona: "Platform Admin",
    description: "Approved support access, session scope, tenant consent, audit export, and revocation.",
    filters: ["Tenant", "Support user", "Status", "Date range"],
    exports: ["CSV"],
    status: "Planned",
    route: "/support",
  },
];

export const reportCategories = ["All", "HR Core", "Attendance", "Payroll Finance", "Compliance", "SaaS Ops"] as const;
