from django.urls import path

from apps.common.api_views import (
    HrAdminAttendancePolicyDetailView,
    HrAdminAttendancePolicyDetachView,
    HrAdminAttendancePolicyPreviewView,
    HrAdminAttendancePolicyAssignmentConflictView,
    HrAdminAttendancePolicyAssignmentResolutionView,
    HrAdminAttendancePolicyAssignmentDetailView,
    HrAdminAttendancePolicyAssignmentListCreateView,
    HrAdminAttendanceOperationOptionsView,
    HrAdminAttendanceRecordBulkActionView,
    HrAdminAttendanceRecordDetailView,
    HrAdminLifecycleOwnerBulkActionView,
    HrAdminLifecycleStatusBulkActionView,
    HrAdminAttendancePolicyListCreateView,
    HrAdminAttendanceRegularizationApproveView,
    HrAdminAttendanceRegularizationDetailView,
    HrAdminAttendanceRegularizationRejectView,
    HrAdminAttendanceRegularizationListView,
    HrAdminAttendanceRecordListView,
    HrAdminDocumentCategoryDetailView,
    HrAdminDocumentCategoryListCreateView,
    HrAdminDashboardView,
    HrAdminReportExportView,
    HrAdminDocumentOptionsView,
    HrAdminDocumentRequirementRuleDetailView,
    HrAdminDocumentRequirementRuleListCreateView,
    HrAdminEmployeeAccessDetailView,
    HrAdminEmployeeAccessOptionsView,
    HrAdminEmployeeDetailView,
    HrAdminEmployeeDocumentDetailView,
    HrAdminEmployeeDocumentDownloadView,
    HrAdminEmployeeDocumentListView,
    HrAdminEmployeeDocumentReminderActionView,
    HrAdminGeneratedLetterDetailView,
    HrAdminGeneratedLetterDownloadView,
    HrAdminGeneratedLetterListCreateView,
    HrAdminGeneratedLetterPreviewView,
    HrAdminEmployeeShiftAssignmentConflictView,
    HrAdminEmployeeShiftAssignmentDetailView,
    HrAdminEmployeeShiftAssignmentListCreateView,
    HrAdminEmployeeShiftAssignmentResolutionView,
    HrAdminShiftRosterTemplateDetailView,
    HrAdminShiftRosterTemplateListCreateView,
    HrAdminShiftRosterRolloutListView,
    HrAdminShiftRosterTemplateRolloutView,
    HrAdminEmployeeFormOptionsView,
    HrAdminEmployeeListView,
    HrAdminExitDetailView,
    HrAdminExitListCreateView,
    HrAdminHolidayCalendarDetailView,
    HrAdminHolidayCalendarDetachView,
    HrAdminHolidayCalendarListCreateView,
    HrAdminLeaveTypeDetailView,
    HrAdminLeaveTypeDetachView,
    HrAdminLeaveTypeListCreateView,
    HrAdminLeavePolicyAssignmentDetailView,
    HrAdminLeavePolicyAssignmentListCreateView,
    HrAdminLeavePolicyAssignmentConflictView,
    HrAdminLeavePolicyAssignmentResolutionView,
    HrAdminLeaveBalanceListView,
    HrAdminLeaveBalanceActionView,
    HrAdminLeaveBalanceTransactionListView,
    HrAdminLeaveBalanceTransactionReviewView,
    HrAdminLeavePolicyDetailView,
    HrAdminLeavePolicyDetachView,
    HrAdminLeavePolicyListCreateView,
    HrAdminLeavePolicyPreviewView,
    HrAdminLifecycleOptionsView,
    HrAdminLifecycleQueueView,
    HrAdminMovementDetailView,
    HrAdminMovementListCreateView,
    HrAdminNotificationDetailView,
    HrAdminNotificationChannelConfigurationDetailView,
    HrAdminNotificationChannelConfigurationListCreateView,
    HrAdminNotificationDiagnosticsView,
    HrAdminNotificationEventDefinitionDetailView,
    HrAdminNotificationEventDefinitionListCreateView,
    HrAdminNotificationEventPreviewView,
    HrAdminNotificationEventTestSendView,
    HrAdminNotificationListView,
    HrAdminNotificationOptionsView,
    HrAdminNotificationBulkRetryView,
    HrAdminNotificationRetryView,
    HrAdminNotificationTemplateDetailView,
    HrAdminNotificationTemplateListCreateView,
    HrAdminNotificationTemplatePreviewView,
    HrAdminNotificationTemplateTestSendView,
    HrAdminOnboardingDetailView,
    HrAdminOnboardingListCreateView,
    HrAdminOrganizationFormOptionsView,
    HrAdminOrganizationSectionDetailView,
    HrAdminOrganizationSectionListCreateView,
    HrAdminOrganizationSnapshotView,
    HrAdminPayGroupAssignmentDetailView,
    HrAdminPayGroupAssignmentListCreateView,
    HrAdminPayGroupDetailView,
    HrAdminPayGroupListCreateView,
    HrAdminPayrollAdjustmentApplyView,
    HrAdminPayrollAdjustmentApproveView,
    HrAdminPayrollAdjustmentListCreateView,
    HrAdminPayrollAdjustmentRejectView,
    HrAdminPayrollAdjustmentSetupView,
    HrAdminPayrollAdjustmentSubmitView,
    HrAdminPayrollCalendarDetailView,
    HrAdminPayrollCalendarListCreateView,
    HrAdminPayrollCalculationSetupView,
    HrAdminPayrollInputSnapshotDetailView,
    HrAdminPayrollInputSnapshotListCreateView,
    HrAdminPayrollInputSnapshotSetupView,
    HrAdminPayrollPeriodDetailView,
    HrAdminPayrollPeriodListCreateView,
    HrAdminPayrollReadinessView,
    HrAdminPayrollRuleDefinitionDetailView,
    HrAdminPayrollRuleDefinitionListCreateView,
    HrAdminPayrollRulesSetupView,
    HrAdminPayrollRuleVersionDetailView,
    HrAdminPayrollRuleVersionEvaluateView,
    HrAdminPayrollRuleVersionListCreateView,
    HrAdminPayrollFinanceHandoffSetupView,
    HrAdminPayrollFinanceHandoffTransmitView,
    HrAdminPayrollOutputArtifactDownloadView,
    HrAdminPayrollOutputBatchPublishView,
    HrAdminPayrollOutputBatchGenerateFinanceHandoffView,
    HrAdminPayrollOutputSetupView,
    HrAdminPayrollRunDraftCalculateView,
    HrAdminPayrollRunDetailView,
    HrAdminPayrollRunListCreateView,
    HrAdminPayrollRunLockInputsView,
    HrAdminPayrollReviewApproveView,
    HrAdminPayrollReviewExceptionDecisionView,
    HrAdminPayrollReviewExceptionListCreateView,
    HrAdminPayrollReviewLockView,
    HrAdminPayrollReviewRejectView,
    HrAdminPayrollReviewGenerateOutputsView,
    HrAdminPayrollReviewSetupView,
    HrAdminPayrollReviewSubmitView,
    HrAdminPayrollRunOpenReviewView,
    HrAdminPayrollSetupView,
    HrAdminPayrollSettlementApplyView,
    HrAdminPayrollSettlementApproveView,
    HrAdminPayrollSettlementLineListCreateView,
    HrAdminPayrollSettlementListCreateView,
    HrAdminPayrollSettlementRejectView,
    HrAdminPayrollSettlementSetupView,
    HrAdminPayrollSettlementSubmitView,
    HrAdminPolicyOptionsView,
    HrAdminProbationReviewDetailView,
    HrAdminProbationReviewListCreateView,
    HrAdminEmployeeSalaryAssignmentDetailView,
    HrAdminEmployeeSalaryAssignmentListCreateView,
    HrAdminSalaryComponentDetailView,
    HrAdminSalaryComponentListCreateView,
    HrAdminSalarySetupView,
    HrAdminSalaryStructureComponentDetailView,
    HrAdminSalaryStructureComponentListCreateView,
    HrAdminSalaryStructureDetailView,
    HrAdminSalaryStructureListCreateView,
    HrAdminSalaryStructureVersionDetailView,
    HrAdminSalaryStructureVersionListCreateView,
    HrAdminShiftDetailView,
    HrAdminShiftDetachView,
    HrAdminShiftListCreateView,
    HrAdminWorkflowOptionsView,
    HrAdminWorkflowTraceDetailView,
    HrAdminWorkflowTraceListView,
    HrAdminWorkflowTemplateAssignmentDetailView,
    HrAdminWorkflowTemplateAssignmentListCreateView,
    HrAdminWorkflowTemplateDetailView,
    HrAdminWorkflowTemplateListCreateView,
    ManagerAttendanceRegularizationDetailView,
    ManagerPendingAttendanceRegularizationListView,
    ManagerAttendanceRegularizationApproveView,
    ManagerAttendanceRegularizationRejectView,
    ManagerNotificationDetailView,
    ManagerNotificationListView,
    ManagerLeaveRequestDetailView,
    ManagerPendingLeaveRequestListView,
    ManagerLeaveRequestApproveView,
    ManagerLeaveRequestRejectView,
    ManagerTeamSummaryView,
    MeAttendanceRecordListView,
    MeAttendanceRegularizationDetailView,
    MeAttendanceRegularizationListCreateView,
    MeAttendanceSummaryView,
    MeDashboardView,
    MeDocumentCenterView,
    MeEmployeeDocumentDownloadView,
    MeEmployeeDocumentListCreateView,
    MeNotificationDetailView,
    MeNotificationListView,
    MeLeaveRequestDetailView,
    MeLeaveRequestWithdrawView,
    MeLeaveRequestCancelView,
    MeLeaveRequestListCreateView,
    MeLeaveSummaryView,
    MeLeaveTypeListView,
    MeProfileView,
)


urlpatterns = [
    path("hr-admin/dashboard/", HrAdminDashboardView.as_view(), name="hr-admin-dashboard"),
    path("hr-admin/payroll-readiness/", HrAdminPayrollReadinessView.as_view(), name="hr-admin-payroll-readiness"),
    path("hr-admin/payroll-setup/", HrAdminPayrollSetupView.as_view(), name="hr-admin-payroll-setup"),
    path("hr-admin/payroll-calculation-setup/", HrAdminPayrollCalculationSetupView.as_view(), name="hr-admin-payroll-calculation-setup"),
    path("hr-admin/payroll-review-setup/", HrAdminPayrollReviewSetupView.as_view(), name="hr-admin-payroll-review-setup"),
    path("hr-admin/payroll-output-setup/", HrAdminPayrollOutputSetupView.as_view(), name="hr-admin-payroll-output-setup"),
    path("hr-admin/payroll-finance-handoff-setup/", HrAdminPayrollFinanceHandoffSetupView.as_view(), name="hr-admin-payroll-finance-handoff-setup"),
    path("hr-admin/payroll-adjustment-setup/", HrAdminPayrollAdjustmentSetupView.as_view(), name="hr-admin-payroll-adjustment-setup"),
    path("hr-admin/payroll-settlement-setup/", HrAdminPayrollSettlementSetupView.as_view(), name="hr-admin-payroll-settlement-setup"),
    path("hr-admin/payroll-input-snapshot-setup/", HrAdminPayrollInputSnapshotSetupView.as_view(), name="hr-admin-payroll-input-snapshot-setup"),
    path("hr-admin/payroll-runs/", HrAdminPayrollRunListCreateView.as_view(), name="hr-admin-payroll-run-list-create"),
    path("hr-admin/payroll-runs/<uuid:item_id>/lock-inputs/", HrAdminPayrollRunLockInputsView.as_view(), name="hr-admin-payroll-run-lock-inputs"),
    path("hr-admin/payroll-runs/<uuid:item_id>/calculate-draft/", HrAdminPayrollRunDraftCalculateView.as_view(), name="hr-admin-payroll-run-calculate-draft"),
    path("hr-admin/payroll-runs/<uuid:item_id>/open-review/", HrAdminPayrollRunOpenReviewView.as_view(), name="hr-admin-payroll-run-open-review"),
    path("hr-admin/payroll-reviews/<uuid:item_id>/submit/", HrAdminPayrollReviewSubmitView.as_view(), name="hr-admin-payroll-review-submit"),
    path("hr-admin/payroll-reviews/<uuid:item_id>/approve/", HrAdminPayrollReviewApproveView.as_view(), name="hr-admin-payroll-review-approve"),
    path("hr-admin/payroll-reviews/<uuid:item_id>/reject/", HrAdminPayrollReviewRejectView.as_view(), name="hr-admin-payroll-review-reject"),
    path("hr-admin/payroll-reviews/<uuid:item_id>/lock/", HrAdminPayrollReviewLockView.as_view(), name="hr-admin-payroll-review-lock"),
    path("hr-admin/payroll-reviews/<uuid:item_id>/generate-outputs/", HrAdminPayrollReviewGenerateOutputsView.as_view(), name="hr-admin-payroll-review-generate-outputs"),
    path("hr-admin/payroll-reviews/<uuid:item_id>/exceptions/", HrAdminPayrollReviewExceptionListCreateView.as_view(), name="hr-admin-payroll-review-exception-list-create"),
    path("hr-admin/payroll-review-exceptions/<uuid:item_id>/decision/", HrAdminPayrollReviewExceptionDecisionView.as_view(), name="hr-admin-payroll-review-exception-decision"),
    path("hr-admin/payroll-output-batches/<uuid:item_id>/publish/", HrAdminPayrollOutputBatchPublishView.as_view(), name="hr-admin-payroll-output-batch-publish"),
    path("hr-admin/payroll-output-artifacts/<uuid:item_id>/download/", HrAdminPayrollOutputArtifactDownloadView.as_view(), name="hr-admin-payroll-output-artifact-download"),
    path("hr-admin/payroll-output-batches/<uuid:item_id>/generate-finance-handoff/", HrAdminPayrollOutputBatchGenerateFinanceHandoffView.as_view(), name="hr-admin-payroll-output-batch-generate-finance-handoff"),
    path("hr-admin/payroll-finance-handoffs/<uuid:item_id>/transmit/", HrAdminPayrollFinanceHandoffTransmitView.as_view(), name="hr-admin-payroll-finance-handoff-transmit"),
    path("hr-admin/payroll-runs/<uuid:item_id>/", HrAdminPayrollRunDetailView.as_view(), name="hr-admin-payroll-run-detail"),
    path("hr-admin/payroll-adjustments/", HrAdminPayrollAdjustmentListCreateView.as_view(), name="hr-admin-payroll-adjustment-list-create"),
    path("hr-admin/payroll-adjustments/<uuid:item_id>/submit/", HrAdminPayrollAdjustmentSubmitView.as_view(), name="hr-admin-payroll-adjustment-submit"),
    path("hr-admin/payroll-adjustments/<uuid:item_id>/approve/", HrAdminPayrollAdjustmentApproveView.as_view(), name="hr-admin-payroll-adjustment-approve"),
    path("hr-admin/payroll-adjustments/<uuid:item_id>/reject/", HrAdminPayrollAdjustmentRejectView.as_view(), name="hr-admin-payroll-adjustment-reject"),
    path("hr-admin/payroll-adjustments/<uuid:item_id>/apply/", HrAdminPayrollAdjustmentApplyView.as_view(), name="hr-admin-payroll-adjustment-apply"),
    path("hr-admin/payroll-settlements/", HrAdminPayrollSettlementListCreateView.as_view(), name="hr-admin-payroll-settlement-list-create"),
    path("hr-admin/payroll-settlements/<uuid:item_id>/lines/", HrAdminPayrollSettlementLineListCreateView.as_view(), name="hr-admin-payroll-settlement-line-list-create"),
    path("hr-admin/payroll-settlements/<uuid:item_id>/submit/", HrAdminPayrollSettlementSubmitView.as_view(), name="hr-admin-payroll-settlement-submit"),
    path("hr-admin/payroll-settlements/<uuid:item_id>/approve/", HrAdminPayrollSettlementApproveView.as_view(), name="hr-admin-payroll-settlement-approve"),
    path("hr-admin/payroll-settlements/<uuid:item_id>/reject/", HrAdminPayrollSettlementRejectView.as_view(), name="hr-admin-payroll-settlement-reject"),
    path("hr-admin/payroll-settlements/<uuid:item_id>/apply/", HrAdminPayrollSettlementApplyView.as_view(), name="hr-admin-payroll-settlement-apply"),
    path("hr-admin/payroll-input-snapshots/", HrAdminPayrollInputSnapshotListCreateView.as_view(), name="hr-admin-payroll-input-snapshot-list-create"),
    path("hr-admin/payroll-input-snapshots/<uuid:item_id>/", HrAdminPayrollInputSnapshotDetailView.as_view(), name="hr-admin-payroll-input-snapshot-detail"),
    path("hr-admin/payroll-rules-setup/", HrAdminPayrollRulesSetupView.as_view(), name="hr-admin-payroll-rules-setup"),
    path("hr-admin/payroll-rule-definitions/", HrAdminPayrollRuleDefinitionListCreateView.as_view(), name="hr-admin-payroll-rule-definition-list-create"),
    path("hr-admin/payroll-rule-definitions/<uuid:item_id>/", HrAdminPayrollRuleDefinitionDetailView.as_view(), name="hr-admin-payroll-rule-definition-detail"),
    path("hr-admin/payroll-rule-versions/", HrAdminPayrollRuleVersionListCreateView.as_view(), name="hr-admin-payroll-rule-version-list-create"),
    path("hr-admin/payroll-rule-versions/<uuid:item_id>/evaluate/", HrAdminPayrollRuleVersionEvaluateView.as_view(), name="hr-admin-payroll-rule-version-evaluate"),
    path("hr-admin/payroll-rule-versions/<uuid:item_id>/", HrAdminPayrollRuleVersionDetailView.as_view(), name="hr-admin-payroll-rule-version-detail"),
    path("hr-admin/payroll-calendars/", HrAdminPayrollCalendarListCreateView.as_view(), name="hr-admin-payroll-calendar-list-create"),
    path("hr-admin/payroll-calendars/<uuid:item_id>/", HrAdminPayrollCalendarDetailView.as_view(), name="hr-admin-payroll-calendar-detail"),
    path("hr-admin/payroll-periods/", HrAdminPayrollPeriodListCreateView.as_view(), name="hr-admin-payroll-period-list-create"),
    path("hr-admin/payroll-periods/<uuid:item_id>/", HrAdminPayrollPeriodDetailView.as_view(), name="hr-admin-payroll-period-detail"),
    path("hr-admin/pay-groups/", HrAdminPayGroupListCreateView.as_view(), name="hr-admin-pay-group-list-create"),
    path("hr-admin/pay-groups/<uuid:item_id>/", HrAdminPayGroupDetailView.as_view(), name="hr-admin-pay-group-detail"),
    path("hr-admin/pay-group-assignments/", HrAdminPayGroupAssignmentListCreateView.as_view(), name="hr-admin-pay-group-assignment-list-create"),
    path("hr-admin/pay-group-assignments/<uuid:item_id>/", HrAdminPayGroupAssignmentDetailView.as_view(), name="hr-admin-pay-group-assignment-detail"),
    path("hr-admin/salary-setup/", HrAdminSalarySetupView.as_view(), name="hr-admin-salary-setup"),
    path("hr-admin/salary-components/", HrAdminSalaryComponentListCreateView.as_view(), name="hr-admin-salary-component-list-create"),
    path("hr-admin/salary-components/<uuid:item_id>/", HrAdminSalaryComponentDetailView.as_view(), name="hr-admin-salary-component-detail"),
    path("hr-admin/salary-structures/", HrAdminSalaryStructureListCreateView.as_view(), name="hr-admin-salary-structure-list-create"),
    path("hr-admin/salary-structures/<uuid:item_id>/", HrAdminSalaryStructureDetailView.as_view(), name="hr-admin-salary-structure-detail"),
    path("hr-admin/salary-structure-versions/", HrAdminSalaryStructureVersionListCreateView.as_view(), name="hr-admin-salary-structure-version-list-create"),
    path("hr-admin/salary-structure-versions/<uuid:item_id>/", HrAdminSalaryStructureVersionDetailView.as_view(), name="hr-admin-salary-structure-version-detail"),
    path("hr-admin/salary-structure-components/", HrAdminSalaryStructureComponentListCreateView.as_view(), name="hr-admin-salary-structure-component-list-create"),
    path("hr-admin/salary-structure-components/<uuid:item_id>/", HrAdminSalaryStructureComponentDetailView.as_view(), name="hr-admin-salary-structure-component-detail"),
    path("hr-admin/employee-salary-assignments/", HrAdminEmployeeSalaryAssignmentListCreateView.as_view(), name="hr-admin-employee-salary-assignment-list-create"),
    path("hr-admin/employee-salary-assignments/<uuid:item_id>/", HrAdminEmployeeSalaryAssignmentDetailView.as_view(), name="hr-admin-employee-salary-assignment-detail"),
    path("hr-admin/reports/exports/<slug:report_key>/", HrAdminReportExportView.as_view(), name="hr-admin-report-export"),
    path("hr-admin/attendance-operations/options/", HrAdminAttendanceOperationOptionsView.as_view(), name="hr-admin-attendance-operations-options"),
    path("hr-admin/shifts/", HrAdminShiftListCreateView.as_view(), name="hr-admin-shift-list-create"),
    path("hr-admin/shifts/<uuid:item_id>/detach/", HrAdminShiftDetachView.as_view(), name="hr-admin-shift-detach"),
    path("hr-admin/shifts/<uuid:item_id>/", HrAdminShiftDetailView.as_view(), name="hr-admin-shift-detail"),
    path("hr-admin/holiday-calendars/", HrAdminHolidayCalendarListCreateView.as_view(), name="hr-admin-holiday-calendar-list-create"),
    path("hr-admin/holiday-calendars/<uuid:item_id>/detach/", HrAdminHolidayCalendarDetachView.as_view(), name="hr-admin-holiday-calendar-detach"),
    path("hr-admin/holiday-calendars/<uuid:item_id>/", HrAdminHolidayCalendarDetailView.as_view(), name="hr-admin-holiday-calendar-detail"),
    path("hr-admin/attendance-records/", HrAdminAttendanceRecordListView.as_view(), name="hr-admin-attendance-record-list"),
    path("hr-admin/attendance-records/bulk-actions/", HrAdminAttendanceRecordBulkActionView.as_view(), name="hr-admin-attendance-record-bulk-actions"),
    path("hr-admin/employee-shift-assignments/", HrAdminEmployeeShiftAssignmentListCreateView.as_view(), name="hr-admin-employee-shift-assignment-list-create"),
    path("hr-admin/employee-shift-assignments/conflicts/", HrAdminEmployeeShiftAssignmentConflictView.as_view(), name="hr-admin-employee-shift-assignment-conflicts"),
    path("hr-admin/employee-shift-assignments/resolve/", HrAdminEmployeeShiftAssignmentResolutionView.as_view(), name="hr-admin-employee-shift-assignment-resolve"),
    path("hr-admin/employee-shift-assignments/<uuid:item_id>/", HrAdminEmployeeShiftAssignmentDetailView.as_view(), name="hr-admin-employee-shift-assignment-detail"),
    path("hr-admin/shift-roster-templates/", HrAdminShiftRosterTemplateListCreateView.as_view(), name="hr-admin-shift-roster-template-list-create"),
    path("hr-admin/shift-roster-rollouts/", HrAdminShiftRosterRolloutListView.as_view(), name="hr-admin-shift-roster-rollout-list"),
    path("hr-admin/shift-roster-templates/rollout/", HrAdminShiftRosterTemplateRolloutView.as_view(), name="hr-admin-shift-roster-template-rollout"),
    path("hr-admin/shift-roster-templates/<uuid:item_id>/", HrAdminShiftRosterTemplateDetailView.as_view(), name="hr-admin-shift-roster-template-detail"),
    path("hr-admin/lifecycle-owner-bulk-actions/", HrAdminLifecycleOwnerBulkActionView.as_view(), name="hr-admin-lifecycle-owner-bulk-actions"),
    path("hr-admin/lifecycle-status-bulk-actions/", HrAdminLifecycleStatusBulkActionView.as_view(), name="hr-admin-lifecycle-status-bulk-actions"),
    path("hr-admin/attendance-records/<uuid:item_id>/", HrAdminAttendanceRecordDetailView.as_view(), name="hr-admin-attendance-record-detail"),
    path("hr-admin/attendance-regularizations/", HrAdminAttendanceRegularizationListView.as_view(), name="hr-admin-attendance-regularization-list"),
    path("hr-admin/attendance-regularizations/<uuid:item_id>/", HrAdminAttendanceRegularizationDetailView.as_view(), name="hr-admin-attendance-regularization-detail"),
    path("hr-admin/attendance-regularizations/<uuid:item_id>/approve/", HrAdminAttendanceRegularizationApproveView.as_view(), name="hr-admin-attendance-regularization-approve"),
    path("hr-admin/attendance-regularizations/<uuid:item_id>/reject/", HrAdminAttendanceRegularizationRejectView.as_view(), name="hr-admin-attendance-regularization-reject"),
    path("hr-admin/policy-options/", HrAdminPolicyOptionsView.as_view(), name="hr-admin-policy-options"),
    path("hr-admin/leave-types/", HrAdminLeaveTypeListCreateView.as_view(), name="hr-admin-leave-type-list-create"),
    path("hr-admin/leave-types/<uuid:item_id>/detach/", HrAdminLeaveTypeDetachView.as_view(), name="hr-admin-leave-type-detach"),
    path("hr-admin/leave-types/<uuid:item_id>/", HrAdminLeaveTypeDetailView.as_view(), name="hr-admin-leave-type-detail"),
    path("hr-admin/leave-policies/", HrAdminLeavePolicyListCreateView.as_view(), name="hr-admin-leave-policy-list-create"),
    path("hr-admin/leave-policies/<uuid:item_id>/detach/", HrAdminLeavePolicyDetachView.as_view(), name="hr-admin-leave-policy-detach"),
    path("hr-admin/leave-policies/<uuid:item_id>/", HrAdminLeavePolicyDetailView.as_view(), name="hr-admin-leave-policy-detail"),
    path("hr-admin/leave-policies/preview/", HrAdminLeavePolicyPreviewView.as_view(), name="hr-admin-leave-policy-preview"),
    path("hr-admin/leave-policy-assignments/conflicts/", HrAdminLeavePolicyAssignmentConflictView.as_view(), name="hr-admin-leave-policy-assignment-conflicts"),
    path("hr-admin/leave-policy-assignments/resolve/", HrAdminLeavePolicyAssignmentResolutionView.as_view(), name="hr-admin-leave-policy-assignment-resolve"),
    path("hr-admin/leave-policy-assignments/", HrAdminLeavePolicyAssignmentListCreateView.as_view(), name="hr-admin-leave-policy-assignment-list-create"),
    path("hr-admin/leave-policy-assignments/<uuid:item_id>/", HrAdminLeavePolicyAssignmentDetailView.as_view(), name="hr-admin-leave-policy-assignment-detail"),
    path("hr-admin/leave-balances/", HrAdminLeaveBalanceListView.as_view(), name="hr-admin-leave-balance-list"),
    path("hr-admin/leave-balances/actions/", HrAdminLeaveBalanceActionView.as_view(), name="hr-admin-leave-balance-actions"),
    path("hr-admin/leave-balances/transactions/", HrAdminLeaveBalanceTransactionListView.as_view(), name="hr-admin-leave-balance-transactions"),
    path("hr-admin/leave-balances/transactions/<uuid:item_id>/review/", HrAdminLeaveBalanceTransactionReviewView.as_view(), name="hr-admin-leave-balance-transaction-review"),
    path("hr-admin/attendance-policies/", HrAdminAttendancePolicyListCreateView.as_view(), name="hr-admin-attendance-policy-list-create"),
    path("hr-admin/attendance-policies/<uuid:item_id>/detach/", HrAdminAttendancePolicyDetachView.as_view(), name="hr-admin-attendance-policy-detach"),
    path("hr-admin/attendance-policies/<uuid:item_id>/", HrAdminAttendancePolicyDetailView.as_view(), name="hr-admin-attendance-policy-detail"),
    path("hr-admin/attendance-policies/preview/", HrAdminAttendancePolicyPreviewView.as_view(), name="hr-admin-attendance-policy-preview"),
    path("hr-admin/attendance-policy-assignments/conflicts/", HrAdminAttendancePolicyAssignmentConflictView.as_view(), name="hr-admin-attendance-policy-assignment-conflicts"),
    path("hr-admin/attendance-policy-assignments/resolve/", HrAdminAttendancePolicyAssignmentResolutionView.as_view(), name="hr-admin-attendance-policy-assignment-resolve"),
    path("hr-admin/attendance-policy-assignments/", HrAdminAttendancePolicyAssignmentListCreateView.as_view(), name="hr-admin-attendance-policy-assignment-list-create"),
    path("hr-admin/attendance-policy-assignments/<uuid:item_id>/", HrAdminAttendancePolicyAssignmentDetailView.as_view(), name="hr-admin-attendance-policy-assignment-detail"),
    path("hr-admin/workflow-options/", HrAdminWorkflowOptionsView.as_view(), name="hr-admin-workflow-options"),
    path("hr-admin/workflow-traces/", HrAdminWorkflowTraceListView.as_view(), name="hr-admin-workflow-trace-list"),
    path("hr-admin/workflow-traces/<uuid:item_id>/", HrAdminWorkflowTraceDetailView.as_view(), name="hr-admin-workflow-trace-detail"),
    path("hr-admin/workflow-templates/", HrAdminWorkflowTemplateListCreateView.as_view(), name="hr-admin-workflow-template-list-create"),
    path("hr-admin/workflow-templates/<uuid:item_id>/", HrAdminWorkflowTemplateDetailView.as_view(), name="hr-admin-workflow-template-detail"),
    path("hr-admin/workflow-template-assignments/", HrAdminWorkflowTemplateAssignmentListCreateView.as_view(), name="hr-admin-workflow-template-assignment-list-create"),
    path("hr-admin/workflow-template-assignments/<uuid:item_id>/", HrAdminWorkflowTemplateAssignmentDetailView.as_view(), name="hr-admin-workflow-template-assignment-detail"),
    path("hr-admin/document-options/", HrAdminDocumentOptionsView.as_view(), name="hr-admin-document-options"),
    path("hr-admin/document-categories/", HrAdminDocumentCategoryListCreateView.as_view(), name="hr-admin-document-category-list-create"),
    path("hr-admin/document-categories/<uuid:item_id>/", HrAdminDocumentCategoryDetailView.as_view(), name="hr-admin-document-category-detail"),
    path("hr-admin/document-requirements/", HrAdminDocumentRequirementRuleListCreateView.as_view(), name="hr-admin-document-requirement-list-create"),
    path("hr-admin/document-requirements/<uuid:item_id>/", HrAdminDocumentRequirementRuleDetailView.as_view(), name="hr-admin-document-requirement-detail"),
    path("hr-admin/employee-documents/", HrAdminEmployeeDocumentListView.as_view(), name="hr-admin-employee-document-list"),
    path("hr-admin/employee-documents/reminders/", HrAdminEmployeeDocumentReminderActionView.as_view(), name="hr-admin-employee-document-reminders"),
    path("hr-admin/employee-documents/<uuid:item_id>/download/", HrAdminEmployeeDocumentDownloadView.as_view(), name="hr-admin-employee-document-download"),
    path("hr-admin/employee-documents/<uuid:item_id>/", HrAdminEmployeeDocumentDetailView.as_view(), name="hr-admin-employee-document-detail"),
    path("hr-admin/generated-letters/preview/", HrAdminGeneratedLetterPreviewView.as_view(), name="hr-admin-generated-letter-preview"),
    path("hr-admin/generated-letters/", HrAdminGeneratedLetterListCreateView.as_view(), name="hr-admin-generated-letter-list-create"),
    path("hr-admin/generated-letters/<uuid:item_id>/download/", HrAdminGeneratedLetterDownloadView.as_view(), name="hr-admin-generated-letter-download"),
    path("hr-admin/generated-letters/<uuid:item_id>/", HrAdminGeneratedLetterDetailView.as_view(), name="hr-admin-generated-letter-detail"),
    path("hr-admin/lifecycle-options/", HrAdminLifecycleOptionsView.as_view(), name="hr-admin-lifecycle-options"),
    path("hr-admin/lifecycle-queue/", HrAdminLifecycleQueueView.as_view(), name="hr-admin-lifecycle-queue"),
    path("hr-admin/onboardings/", HrAdminOnboardingListCreateView.as_view(), name="hr-admin-onboarding-list-create"),
    path("hr-admin/onboardings/<uuid:item_id>/", HrAdminOnboardingDetailView.as_view(), name="hr-admin-onboarding-detail"),
    path("hr-admin/probation-reviews/", HrAdminProbationReviewListCreateView.as_view(), name="hr-admin-probation-review-list-create"),
    path("hr-admin/probation-reviews/<uuid:item_id>/", HrAdminProbationReviewDetailView.as_view(), name="hr-admin-probation-review-detail"),
    path("hr-admin/movements/", HrAdminMovementListCreateView.as_view(), name="hr-admin-movement-list-create"),
    path("hr-admin/movements/<uuid:item_id>/", HrAdminMovementDetailView.as_view(), name="hr-admin-movement-detail"),
    path("hr-admin/exits/", HrAdminExitListCreateView.as_view(), name="hr-admin-exit-list-create"),
    path("hr-admin/exits/<uuid:item_id>/", HrAdminExitDetailView.as_view(), name="hr-admin-exit-detail"),
    path("hr-admin/notification-options/", HrAdminNotificationOptionsView.as_view(), name="hr-admin-notification-options"),
    path("hr-admin/notification-channel-configs/", HrAdminNotificationChannelConfigurationListCreateView.as_view(), name="hr-admin-notification-channel-config-list-create"),
    path("hr-admin/notification-channel-configs/<uuid:item_id>/", HrAdminNotificationChannelConfigurationDetailView.as_view(), name="hr-admin-notification-channel-config-detail"),
    path("hr-admin/notification-templates/preview/", HrAdminNotificationTemplatePreviewView.as_view(), name="hr-admin-notification-template-preview"),
    path("hr-admin/notification-templates/test-send/", HrAdminNotificationTemplateTestSendView.as_view(), name="hr-admin-notification-template-test-send"),
    path("hr-admin/notification-templates/", HrAdminNotificationTemplateListCreateView.as_view(), name="hr-admin-notification-template-list-create"),
    path("hr-admin/notification-templates/<uuid:item_id>/", HrAdminNotificationTemplateDetailView.as_view(), name="hr-admin-notification-template-detail"),
    path("hr-admin/notification-events/preview/", HrAdminNotificationEventPreviewView.as_view(), name="hr-admin-notification-event-preview"),
    path("hr-admin/notification-events/test-send/", HrAdminNotificationEventTestSendView.as_view(), name="hr-admin-notification-event-test-send"),
    path("hr-admin/notification-events/", HrAdminNotificationEventDefinitionListCreateView.as_view(), name="hr-admin-notification-event-list-create"),
    path("hr-admin/notification-diagnostics/", HrAdminNotificationDiagnosticsView.as_view(), name="hr-admin-notification-diagnostics"),
    path("hr-admin/notification-events/<uuid:item_id>/", HrAdminNotificationEventDefinitionDetailView.as_view(), name="hr-admin-notification-event-detail"),
    path("hr-admin/notifications/", HrAdminNotificationListView.as_view(), name="hr-admin-notification-list"),
    path("hr-admin/notifications/bulk-retry/", HrAdminNotificationBulkRetryView.as_view(), name="hr-admin-notification-bulk-retry"),
    path("hr-admin/notifications/<uuid:item_id>/", HrAdminNotificationDetailView.as_view(), name="hr-admin-notification-detail"),
    path("hr-admin/notifications/<uuid:item_id>/retry/", HrAdminNotificationRetryView.as_view(), name="hr-admin-notification-retry"),
    path("hr-admin/employees/access/options/", HrAdminEmployeeAccessOptionsView.as_view(), name="hr-admin-employee-access-options"),
    path("hr-admin/employees/options/", HrAdminEmployeeFormOptionsView.as_view(), name="hr-admin-employee-form-options"),
    path("hr-admin/employees/", HrAdminEmployeeListView.as_view(), name="hr-admin-employee-list"),
    path("hr-admin/employees/<uuid:employee_id>/access/", HrAdminEmployeeAccessDetailView.as_view(), name="hr-admin-employee-access-detail"),
    path("hr-admin/employees/<uuid:employee_id>/", HrAdminEmployeeDetailView.as_view(), name="hr-admin-employee-detail"),
    path("hr-admin/organization/options/", HrAdminOrganizationFormOptionsView.as_view(), name="hr-admin-organization-form-options"),
    path("hr-admin/organization/<slug:section>/", HrAdminOrganizationSectionListCreateView.as_view(), name="hr-admin-organization-section-list-create"),
    path("hr-admin/organization/<slug:section>/<uuid:item_id>/", HrAdminOrganizationSectionDetailView.as_view(), name="hr-admin-organization-section-detail"),
    path("hr-admin/organization/", HrAdminOrganizationSnapshotView.as_view(), name="hr-admin-organization-snapshot"),
    path("me/profile/", MeProfileView.as_view(), name="me-profile"),
    path("me/leave-summary/", MeLeaveSummaryView.as_view(), name="me-leave-summary"),
    path("me/leave-types/", MeLeaveTypeListView.as_view(), name="me-leave-type-list"),
    path("me/attendance-summary/", MeAttendanceSummaryView.as_view(), name="me-attendance-summary"),
    path("me/attendance-records/", MeAttendanceRecordListView.as_view(), name="me-attendance-record-list"),
    path("me/dashboard/", MeDashboardView.as_view(), name="me-dashboard"),
    path("me/document-center/", MeDocumentCenterView.as_view(), name="me-document-center"),
    path("me/notifications/", MeNotificationListView.as_view(), name="me-notification-list"),
    path("me/notifications/<uuid:item_id>/", MeNotificationDetailView.as_view(), name="me-notification-detail"),
    path("me/employee-documents/", MeEmployeeDocumentListCreateView.as_view(), name="me-employee-document-list-create"),
    path("me/employee-documents/<uuid:item_id>/download/", MeEmployeeDocumentDownloadView.as_view(), name="me-employee-document-download"),
    path("me/leave-requests/", MeLeaveRequestListCreateView.as_view(), name="me-leave-request-list-create"),
    path("me/leave-requests/<uuid:request_id>/", MeLeaveRequestDetailView.as_view(), name="me-leave-request-detail"),
    path("me/leave-requests/<uuid:request_id>/withdraw/", MeLeaveRequestWithdrawView.as_view(), name="me-leave-request-withdraw"),
    path("me/leave-requests/<uuid:request_id>/cancel/", MeLeaveRequestCancelView.as_view(), name="me-leave-request-cancel"),
    path("me/attendance-regularizations/", MeAttendanceRegularizationListCreateView.as_view(), name="me-attendance-regularization-list-create"),
    path("me/attendance-regularizations/<uuid:regularization_id>/", MeAttendanceRegularizationDetailView.as_view(), name="me-attendance-regularization-detail"),
    path("manager/team-summary/", ManagerTeamSummaryView.as_view(), name="manager-team-summary"),
    path("manager/notifications/", ManagerNotificationListView.as_view(), name="manager-notification-list"),
    path("manager/notifications/<uuid:item_id>/", ManagerNotificationDetailView.as_view(), name="manager-notification-detail"),
    path("manager/leave-requests/pending/", ManagerPendingLeaveRequestListView.as_view(), name="manager-pending-leave-request-list"),
    path("manager/leave-requests/<uuid:request_id>/", ManagerLeaveRequestDetailView.as_view(), name="manager-leave-request-detail"),
    path("manager/leave-requests/<uuid:request_id>/approve/", ManagerLeaveRequestApproveView.as_view(), name="manager-leave-request-approve"),
    path("manager/leave-requests/<uuid:request_id>/reject/", ManagerLeaveRequestRejectView.as_view(), name="manager-leave-request-reject"),
    path("manager/attendance-regularizations/pending/", ManagerPendingAttendanceRegularizationListView.as_view(), name="manager-pending-attendance-regularization-list"),
    path("manager/attendance-regularizations/<uuid:regularization_id>/", ManagerAttendanceRegularizationDetailView.as_view(), name="manager-attendance-regularization-detail"),
    path("manager/attendance-regularizations/<uuid:regularization_id>/approve/", ManagerAttendanceRegularizationApproveView.as_view(), name="manager-attendance-regularization-approve"),
    path("manager/attendance-regularizations/<uuid:regularization_id>/reject/", ManagerAttendanceRegularizationRejectView.as_view(), name="manager-attendance-regularization-reject"),
]
