# Generated by Django 5.1.15 on 2026-09-05 03:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0002_initial'),
        ('organizations', '0001_initial'),
        ('tenants', '0002_tenant_onboarding_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayGroup',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=60)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('default_currency_code', models.CharField(default='INR', max_length=3)),
                ('config_snapshot', models.JSONField(blank=True, default=dict)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pay_groups', to='organizations.branch')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pay_groups', to='organizations.department')),
                ('employment_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pay_groups', to='organizations.employmenttype')),
                ('legal_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pay_groups', to='organizations.legalentity')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pay_groups', to='organizations.location')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pay_groups', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Pay Group',
                'verbose_name_plural': 'Pay Groups',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PayGroupAssignment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='active', max_length=20)),
                ('config_snapshot', models.JSONField(blank=True, default=dict)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pay_group_assignments', to='employees.employee')),
                ('pay_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='payroll.paygroup')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pay_group_assignments', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Pay Group Assignment',
                'verbose_name_plural': 'Pay Group Assignments',
                'ordering': ['employee__employee_code', '-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='PayrollCalendar',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=60)),
                ('name', models.CharField(max_length=255)),
                ('frequency', models.CharField(choices=[('monthly', 'Monthly'), ('semi_monthly', 'Semi Monthly'), ('biweekly', 'Biweekly'), ('weekly', 'Weekly'), ('custom', 'Custom')], default='monthly', max_length=30)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('currency_code', models.CharField(default='INR', max_length=3)),
                ('period_start_day', models.PositiveSmallIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('config_snapshot', models.JSONField(blank=True, default=dict)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_calendars', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Payroll Calendar',
                'verbose_name_plural': 'Payroll Calendars',
                'ordering': ['name'],
                'unique_together': {('tenant', 'code')},
            },
        ),
        migrations.AddField(
            model_name='paygroup',
            name='calendar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pay_groups', to='payroll.payrollcalendar'),
        ),
        migrations.AlterUniqueTogether(
            name='paygroup',
            unique_together={('tenant', 'code')},
        ),
        migrations.CreateModel(
            name='PayrollPeriod',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=80)),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('pay_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('locked', 'Locked'), ('closed', 'Closed')], default='draft', max_length=20)),
                ('config_snapshot', models.JSONField(blank=True, default=dict)),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='payroll.payrollcalendar')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_periods', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Payroll Period',
                'verbose_name_plural': 'Payroll Periods',
                'ordering': ['-start_date', 'calendar__name'],
                'unique_together': {('calendar', 'code')},
            },
        ),
    ]
