# Generated by Django 5.1.15 on 2026-09-05 03:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_initial'),
        ('payroll', '0001_initial'),
        ('tenants', '0002_tenant_onboarding_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryComponent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=80)),
                ('name', models.CharField(max_length=255)),
                ('component_type', models.CharField(choices=[('earning', 'Earning'), ('deduction', 'Deduction'), ('employer_contribution', 'Employer Contribution'), ('reimbursement', 'Reimbursement'), ('tax', 'Tax'), ('informational', 'Informational')], max_length=40)),
                ('value_type', models.CharField(choices=[('fixed_amount', 'Fixed Amount'), ('percentage', 'Percentage'), ('formula', 'Formula'), ('slab', 'Slab'), ('external_input', 'External Input')], max_length=40)),
                ('formula_ref', models.CharField(blank=True, max_length=160)),
                ('applicability_rule_ref', models.CharField(blank=True, max_length=160)),
                ('rounding_rule_ref', models.CharField(blank=True, max_length=160)),
                ('accounting_mapping_ref', models.CharField(blank=True, max_length=160)),
                ('statutory_treatment_ref', models.CharField(blank=True, max_length=160)),
                ('is_taxable', models.BooleanField(default=False)),
                ('is_proratable', models.BooleanField(default=True)),
                ('payslip_visibility', models.CharField(default='visible', max_length=40)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('retired', 'Retired')], default='draft', max_length=20)),
                ('config_snapshot', models.JSONField(blank=True, default=dict)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_components', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Salary Component',
                'verbose_name_plural': 'Salary Components',
                'ordering': ['component_type', 'name'],
                'unique_together': {('tenant', 'code')},
            },
        ),
        migrations.CreateModel(
            name='SalaryStructure',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=80)),
                ('name', models.CharField(max_length=255)),
                ('currency_code', models.CharField(default='INR', max_length=3)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('retired', 'Retired')], default='draft', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('config_snapshot', models.JSONField(blank=True, default=dict)),
                ('pay_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='salary_structures', to='payroll.paygroup')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_structures', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Salary Structure',
                'verbose_name_plural': 'Salary Structures',
                'ordering': ['name'],
                'unique_together': {('tenant', 'code')},
            },
        ),
        migrations.CreateModel(
            name='SalaryStructureVersion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField(default=1)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('retired', 'Retired')], default='draft', max_length=20)),
                ('annual_ctc', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('currency_code', models.CharField(default='INR', max_length=3)),
                ('config_snapshot', models.JSONField(blank=True, default=dict)),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='payroll.salarystructure')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_structure_versions', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Salary Structure Version',
                'verbose_name_plural': 'Salary Structure Versions',
                'ordering': ['structure__name', '-effective_from'],
                'unique_together': {('structure', 'version')},
            },
        ),
        migrations.CreateModel(
            name='EmployeeSalaryAssignment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('retired', 'Retired')], default='active', max_length=20)),
                ('annual_ctc_override', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('assignment_reason', models.CharField(blank=True, max_length=255)),
                ('config_snapshot', models.JSONField(blank=True, default=dict)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_assignments', to='employees.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_salary_assignments', to='tenants.tenant')),
                ('structure_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_assignments', to='payroll.salarystructureversion')),
            ],
            options={
                'verbose_name': 'Employee Salary Assignment',
                'verbose_name_plural': 'Employee Salary Assignments',
                'ordering': ['employee__employee_code', '-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='SalaryStructureComponent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_order', models.PositiveSmallIntegerField(default=100)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('percentage', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('formula_ref', models.CharField(blank=True, max_length=160)),
                ('calculation_rule_ref', models.CharField(blank=True, max_length=160)),
                ('is_active', models.BooleanField(default=True)),
                ('config_snapshot', models.JSONField(blank=True, default=dict)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='structure_lines', to='payroll.salarycomponent')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_structure_components', to='tenants.tenant')),
                ('structure_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='payroll.salarystructureversion')),
            ],
            options={
                'verbose_name': 'Salary Structure Component',
                'verbose_name_plural': 'Salary Structure Components',
                'ordering': ['display_order', 'component__name'],
                'unique_together': {('structure_version', 'component')},
            },
        ),
    ]
