# Generated by Django 5.1.15 on 2026-09-05 04:25

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_initial'),
        ('payroll', '0002_salarycomponent_salarystructure_and_more'),
        ('tenants', '0002_tenant_onboarding_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollRun',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('collecting_inputs', 'Collecting Inputs'), ('inputs_locked', 'Inputs Locked'), ('calculated', 'Calculated'), ('review', 'Review'), ('approved', 'Approved'), ('locked', 'Locked'), ('cancelled', 'Cancelled')], default='draft', max_length=30)),
                ('input_profile_ref', models.CharField(default='payroll.input.profile.default.v1', max_length=160)),
                ('snapshot_schema_ref', models.CharField(default='payroll.input.snapshot.v1', max_length=160)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('config_snapshot', models.JSONField(blank=True, default=dict)),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_payroll_runs', to=settings.AUTH_USER_MODEL)),
                ('pay_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payroll_runs', to='payroll.paygroup')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='payroll.payrollperiod')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_runs', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Payroll Run',
                'verbose_name_plural': 'Payroll Runs',
                'ordering': ['-period__start_date', 'name'],
                'unique_together': {('tenant', 'code')},
            },
        ),
        migrations.CreateModel(
            name='PayrollInputSnapshot',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('snapshot_status', models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready'), ('warning', 'Warning'), ('blocked', 'Blocked'), ('locked', 'Locked')], default='draft', max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('source_collected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('input_profile_ref', models.CharField(default='payroll.input.profile.default.v1', max_length=160)),
                ('employee_snapshot', models.JSONField(blank=True, default=dict)),
                ('organization_snapshot', models.JSONField(blank=True, default=dict)),
                ('salary_snapshot', models.JSONField(blank=True, default=dict)),
                ('attendance_snapshot', models.JSONField(blank=True, default=dict)),
                ('leave_snapshot', models.JSONField(blank=True, default=dict)),
                ('lifecycle_snapshot', models.JSONField(blank=True, default=dict)),
                ('document_snapshot', models.JSONField(blank=True, default=dict)),
                ('banking_snapshot', models.JSONField(blank=True, default=dict)),
                ('validation_snapshot', models.JSONField(blank=True, default=dict)),
                ('source_hash', models.CharField(blank=True, max_length=64)),
                ('config_snapshot', models.JSONField(blank=True, default=dict)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_input_snapshots', to='employees.employee')),
                ('pay_group_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_input_snapshots', to='payroll.paygroupassignment')),
                ('salary_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_input_snapshots', to='payroll.employeesalaryassignment')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_input_snapshots', to='tenants.tenant')),
                ('payroll_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_snapshots', to='payroll.payrollrun')),
            ],
            options={
                'verbose_name': 'Payroll Input Snapshot',
                'verbose_name_plural': 'Payroll Input Snapshots',
                'ordering': ['employee__employee_code'],
                'unique_together': {('payroll_run', 'employee')},
            },
        ),
    ]
