# Generated by Django 5.1.15 on 2026-09-05 04:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_payrollrun_payrollinputsnapshot'),
        ('tenants', '0002_tenant_onboarding_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollRuleDefinition',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=120)),
                ('name', models.CharField(max_length=255)),
                ('rule_type', models.CharField(choices=[('formula', 'Formula'), ('applicability', 'Applicability'), ('rounding', 'Rounding'), ('proration', 'Proration'), ('validation', 'Validation'), ('statutory', 'Statutory'), ('accounting', 'Accounting')], default='formula', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('config_snapshot', models.JSONField(blank=True, default=dict)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_rule_definitions', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Payroll Rule Definition',
                'verbose_name_plural': 'Payroll Rule Definitions',
                'ordering': ['rule_type', 'name'],
                'unique_together': {('tenant', 'code')},
            },
        ),
        migrations.CreateModel(
            name='PayrollRuleVersion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('retired', 'Retired')], default='draft', max_length=20)),
                ('expression_language', models.CharField(choices=[('safe_expr_v1', 'Safe Expression V1')], default='safe_expr_v1', max_length=30)),
                ('expression', models.TextField()),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('input_schema', models.JSONField(blank=True, default=dict)),
                ('output_schema', models.JSONField(blank=True, default=dict)),
                ('rounding_rule_ref', models.CharField(blank=True, max_length=160)),
                ('config_snapshot', models.JSONField(blank=True, default=dict)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='payroll.payrollruledefinition')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_rule_versions', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Payroll Rule Version',
                'verbose_name_plural': 'Payroll Rule Versions',
                'ordering': ['rule__code', '-version'],
                'unique_together': {('rule', 'version')},
            },
        ),
        migrations.CreateModel(
            name='PayrollRuleEvaluation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('expression', models.TextField()),
                ('context_snapshot', models.JSONField(blank=True, default=dict)),
                ('result_snapshot', models.JSONField(blank=True, default=dict)),
                ('trace_snapshot', models.JSONField(blank=True, default=dict)),
                ('evaluated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_rule_evaluations', to=settings.AUTH_USER_MODEL)),
                ('input_snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rule_evaluations', to='payroll.payrollinputsnapshot')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_rule_evaluations', to='tenants.tenant')),
                ('rule_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluations', to='payroll.payrollruleversion')),
            ],
            options={
                'verbose_name': 'Payroll Rule Evaluation',
                'verbose_name_plural': 'Payroll Rule Evaluations',
                'ordering': ['-created_at'],
            },
        ),
    ]
