# Generated by Django 5.1.15 on 2026-09-05 05:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_initial'),
        ('payroll', '0004_payrollruledefinition_payrollruleversion_and_more'),
        ('tenants', '0002_tenant_onboarding_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollRunCalculation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('completed', 'Completed'), ('failed', 'Failed'), ('superseded', 'Superseded')], default='draft', max_length=20)),
                ('calculation_profile_ref', models.CharField(default='payroll.calculation.profile.default.v1', max_length=160)),
                ('calculated_at', models.DateTimeField(blank=True, null=True)),
                ('rule_selection_snapshot', models.JSONField(blank=True, default=dict)),
                ('totals_snapshot', models.JSONField(blank=True, default=dict)),
                ('error_snapshot', models.JSONField(blank=True, default=dict)),
                ('config_snapshot', models.JSONField(blank=True, default=dict)),
                ('calculated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_run_calculations', to=settings.AUTH_USER_MODEL)),
                ('payroll_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculations', to='payroll.payrollrun')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_run_calculations', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Payroll Run Calculation',
                'verbose_name_plural': 'Payroll Run Calculations',
                'ordering': ['-created_at'],
                'unique_together': {('payroll_run', 'attempt_number')},
            },
        ),
        migrations.CreateModel(
            name='PayrollCalculationLine',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('component_code', models.CharField(max_length=120)),
                ('component_name', models.CharField(max_length=255)),
                ('line_type', models.CharField(default='formula', max_length=60)),
                ('calculation_order', models.PositiveSmallIntegerField(default=100)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('currency_code', models.CharField(default='INR', max_length=3)),
                ('status', models.CharField(choices=[('calculated', 'Calculated'), ('error', 'Error'), ('skipped', 'Skipped')], default='calculated', max_length=20)),
                ('expression', models.TextField(blank=True)),
                ('source_hash', models.CharField(blank=True, max_length=64)),
                ('context_snapshot', models.JSONField(blank=True, default=dict)),
                ('result_snapshot', models.JSONField(blank=True, default=dict)),
                ('trace_snapshot', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('config_snapshot', models.JSONField(blank=True, default=dict)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_calculation_lines', to='employees.employee')),
                ('input_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calculation_lines', to='payroll.payrollinputsnapshot')),
                ('payroll_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculation_lines', to='payroll.payrollrun')),
                ('rule_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calculation_lines', to='payroll.payrollruleversion')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_calculation_lines', to='tenants.tenant')),
                ('calculation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='payroll.payrollruncalculation')),
            ],
            options={
                'verbose_name': 'Payroll Calculation Line',
                'verbose_name_plural': 'Payroll Calculation Lines',
                'ordering': ['employee__employee_code', 'calculation_order', 'component_code'],
                'unique_together': {('calculation', 'input_snapshot', 'rule_version')},
            },
        ),
    ]
