# Generated by Django 5.1.15 on 2026-09-05 05:42

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_initial'),
        ('payroll', '0005_payrollruncalculation_payrollcalculationline'),
        ('tenants', '0002_tenant_onboarding_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollrun',
            name='final_locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='final_locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_locked_payroll_runs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PayrollRunReview',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('open', 'Open'), ('ready_for_approval', 'Ready For Approval'), ('approved', 'Approved'), ('locked', 'Locked'), ('rejected', 'Rejected')], default='open', max_length=30)),
                ('review_profile_ref', models.CharField(default='payroll.review.profile.default.v1', max_length=160)),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('totals_snapshot', models.JSONField(blank=True, default=dict)),
                ('exception_summary_snapshot', models.JSONField(blank=True, default=dict)),
                ('approval_snapshot', models.JSONField(blank=True, default=dict)),
                ('config_snapshot', models.JSONField(blank=True, default=dict)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_payroll_reviews', to=settings.AUTH_USER_MODEL)),
                ('calculation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='review', to='payroll.payrollruncalculation')),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_payroll_reviews', to=settings.AUTH_USER_MODEL)),
                ('opened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opened_payroll_reviews', to=settings.AUTH_USER_MODEL)),
                ('payroll_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='payroll.payrollrun')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_payroll_reviews', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_run_reviews', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Payroll Run Review',
                'verbose_name_plural': 'Payroll Run Reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PayrollRunException',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(default='review', max_length=80)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('blocker', 'Blocker')], default='warning', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('accepted', 'Accepted'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], default='open', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('detail', models.TextField(blank=True)),
                ('decision_reason', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('config_snapshot', models.JSONField(blank=True, default=dict)),
                ('calculation_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_exceptions', to='payroll.payrollcalculationline')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_payroll_exceptions', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_run_exceptions', to='employees.employee')),
                ('input_snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_exceptions', to='payroll.payrollinputsnapshot')),
                ('payroll_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='payroll.payrollrun')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_run_exceptions', to='tenants.tenant')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='payroll.payrollrunreview')),
            ],
            options={
                'verbose_name': 'Payroll Run Exception',
                'verbose_name_plural': 'Payroll Run Exceptions',
                'ordering': ['severity', 'employee__employee_code', 'category', 'title'],
            },
        ),
        migrations.CreateModel(
            name='PayrollRunApproval',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('approval_profile_ref', models.CharField(default='payroll.approval.profile.default.v1', max_length=160)),
                ('config_snapshot', models.JSONField(blank=True, default=dict)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_run_approvals', to=settings.AUTH_USER_MODEL)),
                ('payroll_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='payroll.payrollrun')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_run_approvals', to='tenants.tenant')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='payroll.payrollrunreview')),
            ],
            options={
                'verbose_name': 'Payroll Run Approval',
                'verbose_name_plural': 'Payroll Run Approvals',
                'ordering': ['-created_at'],
            },
        ),
    ]
