# Generated by Django 5.1.15 on 2026-09-05 06:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_initial'),
        ('payroll', '0006_payrollrun_final_locked_at_and_more'),
        ('tenants', '0002_tenant_onboarding_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollOutputBatch',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('generated', 'Generated'), ('published', 'Published'), ('superseded', 'Superseded')], default='generated', max_length=20)),
                ('output_profile_ref', models.CharField(default='payroll.output.profile.default.v1', max_length=160)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('totals_snapshot', models.JSONField(blank=True, default=dict)),
                ('artifact_summary_snapshot', models.JSONField(blank=True, default=dict)),
                ('config_snapshot', models.JSONField(blank=True, default=dict)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_payroll_output_batches', to=settings.AUTH_USER_MODEL)),
                ('payroll_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='output_batches', to='payroll.payrollrun')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_payroll_output_batches', to=settings.AUTH_USER_MODEL)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='output_batches', to='payroll.payrollrunreview')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_output_batches', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Payroll Output Batch',
                'verbose_name_plural': 'Payroll Output Batches',
                'ordering': ['-created_at'],
                'unique_together': {('review', 'output_profile_ref')},
            },
        ),
        migrations.CreateModel(
            name='PayrollOutputArtifact',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('payslip', 'Payslip'), ('register', 'Register'), ('bank_advice', 'Bank Advice'), ('accounting_export', 'Accounting Export'), ('statutory_report', 'Statutory Report')], default='payslip', max_length=40)),
                ('status', models.CharField(choices=[('generated', 'Generated'), ('published', 'Published'), ('voided', 'Voided')], default='generated', max_length=20)),
                ('artifact_key', models.CharField(max_length=180)),
                ('title', models.CharField(max_length=255)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('content_type', models.CharField(default='application/json', max_length=120)),
                ('output_profile_ref', models.CharField(default='payroll.output.profile.default.v1', max_length=160)),
                ('totals_snapshot', models.JSONField(blank=True, default=dict)),
                ('line_snapshot', models.JSONField(blank=True, default=list)),
                ('source_hash', models.CharField(blank=True, max_length=64)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('config_snapshot', models.JSONField(blank=True, default=dict)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payroll_output_artifacts', to='employees.employee')),
                ('input_snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='output_artifacts', to='payroll.payrollinputsnapshot')),
                ('payroll_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='output_artifacts', to='payroll.payrollrun')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_payroll_output_artifacts', to=settings.AUTH_USER_MODEL)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='output_artifacts', to='payroll.payrollrunreview')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_output_artifacts', to='tenants.tenant')),
                ('output_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='payroll.payrolloutputbatch')),
            ],
            options={
                'verbose_name': 'Payroll Output Artifact',
                'verbose_name_plural': 'Payroll Output Artifacts',
                'ordering': ['kind', 'artifact_key'],
                'unique_together': {('output_batch', 'kind', 'artifact_key')},
            },
        ),
    ]
