# Generated by Django 5.1.15 on 2026-09-05 06:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0007_payrolloutputbatch_payrolloutputartifact'),
        ('tenants', '0002_tenant_onboarding_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollFinanceHandoff',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('generated', 'Generated'), ('transmitted', 'Transmitted'), ('accepted', 'Accepted'), ('failed', 'Failed')], default='generated', max_length=20)),
                ('handoff_profile_ref', models.CharField(default='payroll.finance_handoff.profile.default.v1', max_length=160)),
                ('bank_file_profile_ref', models.CharField(default='payroll.bank_file.profile.default.v1', max_length=160)),
                ('accounting_export_profile_ref', models.CharField(default='payroll.accounting_export.profile.default.v1', max_length=160)),
                ('statutory_pack_ref', models.CharField(default='payroll.statutory_pack.default.v1', max_length=160)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('transmitted_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('totals_snapshot', models.JSONField(blank=True, default=dict)),
                ('handoff_summary_snapshot', models.JSONField(blank=True, default=dict)),
                ('config_snapshot', models.JSONField(blank=True, default=dict)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_payroll_finance_handoffs', to=settings.AUTH_USER_MODEL)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_payroll_finance_handoffs', to=settings.AUTH_USER_MODEL)),
                ('output_batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finance_handoffs', to='payroll.payrolloutputbatch')),
                ('payroll_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finance_handoffs', to='payroll.payrollrun')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finance_handoffs', to='payroll.payrollrunreview')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_finance_handoffs', to='tenants.tenant')),
                ('transmitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transmitted_payroll_finance_handoffs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payroll Finance Handoff',
                'verbose_name_plural': 'Payroll Finance Handoffs',
                'ordering': ['-created_at'],
                'unique_together': {('output_batch', 'handoff_profile_ref')},
            },
        ),
    ]
