# Generated by Django 5.1.15 on 2026-09-05 06:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_initial'),
        ('payroll', '0008_payrollfinancehandoff'),
        ('tenants', '0002_tenant_onboarding_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollAdjustment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('arrear', 'Arrear'), ('bonus', 'Bonus'), ('incentive', 'Incentive'), ('reimbursement', 'Reimbursement'), ('loan', 'Loan'), ('advance', 'Advance'), ('deduction', 'Deduction'), ('correction', 'Correction'), ('settlement', 'Settlement')], default='correction', max_length=30)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('applied', 'Applied'), ('voided', 'Voided')], default='draft', max_length=20)),
                ('direction', models.CharField(choices=[('earning', 'Earning'), ('deduction', 'Deduction'), ('reimbursement', 'Reimbursement'), ('employer_contribution', 'Employer Contribution'), ('tax', 'Tax'), ('informational', 'Informational')], default='earning', max_length=40)),
                ('component_code', models.CharField(max_length=120)),
                ('component_name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency_code', models.CharField(default='INR', max_length=3)),
                ('effective_date', models.DateField()),
                ('source_period_start', models.DateField(blank=True, null=True)),
                ('source_period_end', models.DateField(blank=True, null=True)),
                ('adjustment_profile_ref', models.CharField(default='payroll.adjustment.profile.default.v1', max_length=160)),
                ('approval_profile_ref', models.CharField(blank=True, max_length=160)),
                ('source_ref', models.CharField(blank=True, max_length=180)),
                ('reason', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('source_hash', models.CharField(blank=True, max_length=64)),
                ('config_snapshot', models.JSONField(blank=True, default=dict)),
                ('applied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_payroll_adjustments', to=settings.AUTH_USER_MODEL)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_payroll_adjustments', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_adjustments', to='employees.employee')),
                ('input_snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payroll_adjustments', to='payroll.payrollinputsnapshot')),
                ('payroll_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='payroll.payrollrun')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_payroll_adjustments', to=settings.AUTH_USER_MODEL)),
                ('salary_component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payroll_adjustments', to='payroll.salarycomponent')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_payroll_adjustments', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_adjustments', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Payroll Adjustment',
                'verbose_name_plural': 'Payroll Adjustments',
                'ordering': ['-effective_date', 'employee__employee_code', 'component_code'],
                'unique_together': {('payroll_run', 'employee', 'source_ref', 'component_code')},
            },
        ),
    ]
