# Generated by Django 5.1.15 on 2026-09-05 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0009_payrolladjustment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='payrollcalculationline',
            unique_together={('calculation', 'input_snapshot', 'rule_version')},
        ),
        migrations.AddField(
            model_name='payrollcalculationline',
            name='adjustment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='calculation_lines', to='payroll.payrolladjustment'),
        ),
        migrations.AddField(
            model_name='payrollcalculationline',
            name='line_source',
            field=models.CharField(choices=[('rule', 'Rule'), ('adjustment', 'Adjustment')], default='rule', max_length=30),
        ),
        migrations.AlterField(
            model_name='payrollcalculationline',
            name='rule_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='calculation_lines', to='payroll.payrollruleversion'),
        ),
        migrations.AlterUniqueTogether(
            name='payrollcalculationline',
            unique_together={('calculation', 'input_snapshot', 'adjustment'), ('calculation', 'input_snapshot', 'rule_version')},
        ),
    ]
