# Generated by Django 5.1.15 on 2026-09-05 07:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_lifecycle', '0001_initial'),
        ('employees', '0002_initial'),
        ('payroll', '0010_alter_payrollcalculationline_unique_together_and_more'),
        ('tenants', '0002_tenant_onboarding_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollSettlement',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('applied', 'Applied'), ('voided', 'Voided')], default='draft', max_length=20)),
                ('settlement_profile_ref', models.CharField(default='payroll.settlement.profile.default.v1', max_length=160)),
                ('approval_profile_ref', models.CharField(blank=True, max_length=160)),
                ('calculation_profile_ref', models.CharField(blank=True, max_length=160)),
                ('source_ref', models.CharField(blank=True, max_length=180)),
                ('reason', models.TextField(blank=True)),
                ('settlement_date', models.DateField()),
                ('last_working_date', models.DateField(blank=True, null=True)),
                ('currency_code', models.CharField(default='INR', max_length=3)),
                ('totals_snapshot', models.JSONField(blank=True, default=dict)),
                ('source_hash', models.CharField(blank=True, max_length=64)),
                ('config_snapshot', models.JSONField(blank=True, default=dict)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('applied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_payroll_settlements', to=settings.AUTH_USER_MODEL)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_payroll_settlements', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_settlements', to='employees.employee')),
                ('exit_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payroll_settlements', to='employee_lifecycle.employeeexit')),
                ('input_snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payroll_settlements', to='payroll.payrollinputsnapshot')),
                ('payroll_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='payroll.payrollrun')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_payroll_settlements', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_payroll_settlements', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_settlements', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Payroll Settlement',
                'verbose_name_plural': 'Payroll Settlements',
                'ordering': ['-settlement_date', 'employee__employee_code'],
                'unique_together': {('payroll_run', 'employee', 'source_ref')},
            },
        ),
        migrations.CreateModel(
            name='PayrollSettlementLine',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('line_kind', models.CharField(choices=[('salary_proration', 'Salary Proration'), ('leave_encashment', 'Leave Encashment'), ('notice_recovery', 'Notice Recovery'), ('loan_recovery', 'Loan Recovery'), ('advance_recovery', 'Advance Recovery'), ('bonus', 'Bonus'), ('arrear', 'Arrear'), ('gratuity', 'Gratuity'), ('statutory', 'Statutory'), ('other', 'Other')], default='other', max_length=40)),
                ('direction', models.CharField(choices=[('earning', 'Earning'), ('deduction', 'Deduction'), ('reimbursement', 'Reimbursement'), ('employer_contribution', 'Employer Contribution'), ('tax', 'Tax'), ('informational', 'Informational')], default='earning', max_length=40)),
                ('component_code', models.CharField(max_length=120)),
                ('component_name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency_code', models.CharField(default='INR', max_length=3)),
                ('calculation_order', models.PositiveIntegerField(default=900)),
                ('source_ref', models.CharField(blank=True, max_length=180)),
                ('source_hash', models.CharField(blank=True, max_length=64)),
                ('trace_snapshot', models.JSONField(blank=True, default=dict)),
                ('config_snapshot', models.JSONField(blank=True, default=dict)),
                ('salary_component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payroll_settlement_lines', to='payroll.salarycomponent')),
                ('settlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='payroll.payrollsettlement')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_settlement_lines', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Payroll Settlement Line',
                'verbose_name_plural': 'Payroll Settlement Lines',
                'ordering': ['calculation_order', 'component_code'],
                'unique_together': {('settlement', 'source_ref', 'component_code')},
            },
        ),
    ]
