# Generated by Django 5.1.15 on 2026-09-05 08:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_initial'),
        ('payroll', '0011_payrollsettlement_payrollsettlementline'),
        ('tenants', '0002_tenant_onboarding_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollValidationIssue',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('blocker', 'Blocker')], default='warning', max_length=20)),
                ('category', models.CharField(choices=[('source_data', 'Source Data'), ('salary_setup', 'Salary Setup'), ('rule_setup', 'Rule Setup'), ('statutory_setup', 'Statutory Setup'), ('adjustment', 'Adjustment'), ('settlement', 'Settlement'), ('output_readiness', 'Output Readiness')], default='source_data', max_length=40)),
                ('status', models.CharField(choices=[('open', 'Open'), ('accepted', 'Accepted'), ('resolved', 'Resolved')], default='open', max_length=20)),
                ('issue_code', models.CharField(max_length=120)),
                ('title', models.CharField(max_length=255)),
                ('detail', models.TextField(blank=True)),
                ('source_ref', models.CharField(blank=True, max_length=180)),
                ('validation_profile_ref', models.CharField(default='payroll.validation.profile.default.v1', max_length=160)),
                ('source_hash', models.CharField(blank=True, max_length=64)),
                ('context_snapshot', models.JSONField(blank=True, default=dict)),
                ('config_snapshot', models.JSONField(blank=True, default=dict)),
                ('calculation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='validation_issues', to='payroll.payrollruncalculation')),
                ('calculation_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validation_issues', to='payroll.payrollcalculationline')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_validation_issues', to='employees.employee')),
                ('input_snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validation_issues', to='payroll.payrollinputsnapshot')),
                ('payroll_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_issues', to='payroll.payrollrun')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_validation_issues', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Payroll Validation Issue',
                'verbose_name_plural': 'Payroll Validation Issues',
                'ordering': ['-created_at', 'severity', 'category', 'issue_code'],
            },
        ),
    ]
