# Generated by Django 5.1.15 on 2026-09-05 12:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_initial'),
        ('iam', '0001_initial'),
        ('notifications', '0002_notificationchannelconfiguration'),
        ('payroll', '0015_payrolloutputartifact_storage_strategy'),
        ('tenants', '0002_tenant_onboarding_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollArtifactAccessEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('published', 'Published'), ('notified', 'Notified'), ('downloaded', 'Downloaded'), ('read_acknowledged', 'Read Acknowledged'), ('revoked', 'Revoked')], max_length=40)),
                ('status', models.CharField(choices=[('recorded', 'Recorded'), ('failed', 'Failed'), ('revoked', 'Revoked')], default='recorded', max_length=20)),
                ('event_profile_ref', models.CharField(default='payroll.artifact_access.profile.default.v1', max_length=160)),
                ('source_channel_ref', models.CharField(default='employee.portal.v1', max_length=160)),
                ('actor_identifier', models.CharField(blank=True, max_length=180)),
                ('request_identifier', models.CharField(blank=True, max_length=180)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('storage_provider_ref', models.CharField(blank=True, max_length=160)),
                ('storage_key', models.CharField(blank=True, max_length=500)),
                ('storage_object_version', models.CharField(blank=True, max_length=180)),
                ('download_strategy_ref', models.CharField(blank=True, max_length=160)),
                ('checksum_sha256', models.CharField(blank=True, max_length=64)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('metadata_snapshot', models.JSONField(blank=True, default=dict)),
                ('config_snapshot', models.JSONField(blank=True, default=dict)),
                ('actor_membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_artifact_access_events', to='iam.tenantmembership')),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_artifact_access_events', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payroll_artifact_access_events', to='employees.employee')),
                ('notification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_artifact_access_events', to='notifications.notification')),
                ('output_artifact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_events', to='payroll.payrolloutputartifact')),
                ('output_batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='artifact_access_events', to='payroll.payrolloutputbatch')),
                ('payroll_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='artifact_access_events', to='payroll.payrollrun')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='artifact_access_events', to='payroll.payrollrunreview')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_artifact_access_events', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Payroll Artifact Access Event',
                'verbose_name_plural': 'Payroll Artifact Access Events',
                'ordering': ['-created_at'],
            },
        ),
    ]
