# Generated by Django 5.1.15 on 2026-09-05 13:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_initial'),
        ('iam', '0001_initial'),
        ('payroll', '0016_payrollartifactaccessevent'),
        ('tenants', '0002_tenant_onboarding_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrollartifactaccessevent',
            name='event_type',
            field=models.CharField(choices=[('published', 'Published'), ('notified', 'Notified'), ('signed_url_issued', 'Signed URL Issued'), ('downloaded', 'Downloaded'), ('read_acknowledged', 'Read Acknowledged'), ('revoked', 'Revoked')], max_length=40),
        ),
        migrations.CreateModel(
            name='PayrollArtifactSignedAccessGrant',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked'), ('expired', 'Expired')], default='active', max_length=20)),
                ('permission_scope', models.CharField(default='download', max_length=80)),
                ('grant_profile_ref', models.CharField(default='payroll.signed_access.profile.default.v1', max_length=160)),
                ('source_channel_ref', models.CharField(default='employee.portal.v1', max_length=160)),
                ('token_hash', models.CharField(max_length=64)),
                ('token_prefix', models.CharField(blank=True, max_length=16)),
                ('signed_url', models.CharField(blank=True, max_length=1000)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revocation_reason', models.CharField(blank=True, max_length=255)),
                ('access_count', models.PositiveIntegerField(default=0)),
                ('max_access_count', models.PositiveIntegerField(blank=True, null=True)),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True)),
                ('storage_provider_ref', models.CharField(blank=True, max_length=160)),
                ('storage_key', models.CharField(blank=True, max_length=500)),
                ('storage_object_version', models.CharField(blank=True, max_length=180)),
                ('download_strategy_ref', models.CharField(blank=True, max_length=160)),
                ('checksum_sha256', models.CharField(blank=True, max_length=64)),
                ('metadata_snapshot', models.JSONField(blank=True, default=dict)),
                ('config_snapshot', models.JSONField(blank=True, default=dict)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payroll_artifact_signed_access_grants', to='employees.employee')),
                ('issued_by_membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payroll_artifact_signed_access_grants', to='iam.tenantmembership')),
                ('issued_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payroll_artifact_signed_access_grants', to=settings.AUTH_USER_MODEL)),
                ('issued_to_membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_payroll_artifact_signed_access_grants', to='iam.tenantmembership')),
                ('issued_to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_payroll_artifact_signed_access_grants', to=settings.AUTH_USER_MODEL)),
                ('output_artifact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signed_access_grants', to='payroll.payrolloutputartifact')),
                ('output_batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='artifact_signed_access_grants', to='payroll.payrolloutputbatch')),
                ('payroll_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='artifact_signed_access_grants', to='payroll.payrollrun')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='artifact_signed_access_grants', to='payroll.payrollrunreview')),
                ('revoked_by_membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_payroll_artifact_signed_access_grants', to='iam.tenantmembership')),
                ('revoked_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_payroll_artifact_signed_access_grants', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_artifact_signed_access_grants', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Payroll Artifact Signed Access Grant',
                'verbose_name_plural': 'Payroll Artifact Signed Access Grants',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='payrollartifactaccessevent',
            name='signed_access_grant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_events', to='payroll.payrollartifactsignedaccessgrant'),
        ),
    ]
