# Generated by Django 5.1.15 on 2026-09-05 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0018_payrollstatutorypack_payrollstatutorycomponent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrollcalculationline',
            name='line_source',
            field=models.CharField(choices=[('rule', 'Rule'), ('adjustment', 'Adjustment'), ('statutory', 'Statutory')], default='rule', max_length=30),
        ),
    ]
