# Generated by Django 5.1.15 on 2026-09-05 16:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_initial'),
        ('payroll', '0019_alter_payrollcalculationline_line_source'),
        ('tenants', '0002_tenant_onboarding_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeStatutoryDeclaration',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('financial_year_code', models.CharField(max_length=40)),
                ('declaration_profile_ref', models.CharField(default='payroll.statutory.declaration.india.default.v1', max_length=160)),
                ('proof_window_ref', models.CharField(blank=True, max_length=160)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('locked', 'Locked')], default='draft', max_length=20)),
                ('tax_regime', models.CharField(choices=[('old', 'Old Regime'), ('new', 'New Regime'), ('not_declared', 'Not Declared')], default='not_declared', max_length=20)),
                ('declared_total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('verified_total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('source_ref', models.CharField(blank=True, max_length=180)),
                ('source_hash', models.CharField(blank=True, max_length=64)),
                ('config_snapshot', models.JSONField(blank=True, default=dict)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statutory_declarations', to='employees.employee')),
                ('employee_statutory_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='declarations', to='payroll.employeestatutoryprofile')),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_statutory_declarations', to=settings.AUTH_USER_MODEL)),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_statutory_declarations', to=settings.AUTH_USER_MODEL)),
                ('statutory_pack', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_declarations', to='payroll.payrollstatutorypack')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_statutory_declarations', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_statutory_declarations', to='tenants.tenant')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_statutory_declarations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employee Statutory Declaration',
                'verbose_name_plural': 'Employee Statutory Declarations',
                'ordering': ['employee__employee_code', '-financial_year_code', 'declaration_profile_ref'],
                'unique_together': {('tenant', 'employee', 'financial_year_code', 'declaration_profile_ref')},
            },
        ),
        migrations.CreateModel(
            name='EmployeeStatutoryDeclarationItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_kind', models.CharField(choices=[('previous_employment', 'Previous Employment'), ('investment', 'Investment'), ('exemption', 'Exemption'), ('deduction', 'Deduction'), ('rental', 'Rental'), ('other', 'Other')], default='investment', max_length=30)),
                ('section_code', models.CharField(max_length=80)),
                ('component_code', models.CharField(blank=True, max_length=120)),
                ('name', models.CharField(max_length=255)),
                ('declared_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('verified_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('proof_status', models.CharField(choices=[('not_required', 'Not Required'), ('pending', 'Pending'), ('submitted', 'Submitted'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('proof_document_ref', models.CharField(blank=True, max_length=180)),
                ('proof_artifact_key', models.CharField(blank=True, max_length=240)),
                ('proof_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('source_ref', models.CharField(blank=True, max_length=180)),
                ('source_hash', models.CharField(blank=True, max_length=64)),
                ('config_snapshot', models.JSONField(blank=True, default=dict)),
                ('declaration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='payroll.employeestatutorydeclaration')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statutory_declaration_items', to='employees.employee')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_statutory_declaration_items', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_statutory_declaration_items', to='tenants.tenant')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_statutory_declaration_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employee Statutory Declaration Item',
                'verbose_name_plural': 'Employee Statutory Declaration Items',
                'ordering': ['declaration__financial_year_code', 'employee__employee_code', 'section_code', 'component_code'],
                'unique_together': {('declaration', 'section_code', 'component_code')},
            },
        ),
    ]
