# Generated by Django 5.1.15 on 2026-09-05 18:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('payroll', '0020_employeestatutorydeclaration_and_more'),
        ('tenants', '0002_tenant_onboarding_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollStatutoryEmployerRegistration',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('registration_type_ref', models.CharField(max_length=160)),
                ('registration_number', models.CharField(max_length=120)),
                ('employer_identifier', models.CharField(blank=True, max_length=120)),
                ('jurisdiction_ref', models.CharField(blank=True, max_length=160)),
                ('filing_authority_ref', models.CharField(blank=True, max_length=160)),
                ('provider_ref', models.CharField(blank=True, max_length=160)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('retired', 'Retired')], default='active', max_length=20)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('source_ref', models.CharField(blank=True, max_length=180)),
                ('source_hash', models.CharField(blank=True, max_length=64)),
                ('config_snapshot', models.JSONField(blank=True, default=dict)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payroll_statutory_employer_registrations', to='organizations.branch')),
                ('legal_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payroll_statutory_employer_registrations', to='organizations.legalentity')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payroll_statutory_employer_registrations', to='organizations.location')),
                ('statutory_component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employer_registrations', to='payroll.payrollstatutorycomponent')),
                ('statutory_pack', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employer_registrations', to='payroll.payrollstatutorypack')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_statutory_employer_registrations', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Payroll Statutory Employer Registration',
                'verbose_name_plural': 'Payroll Statutory Employer Registrations',
                'ordering': ['statutory_pack__name', 'registration_type_ref', 'name'],
                'unique_together': {('tenant', 'code')},
            },
        ),
        migrations.CreateModel(
            name='PayrollStatutoryFilingCalendar',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=120)),
                ('name', models.CharField(max_length=255)),
                ('filing_type_ref', models.CharField(max_length=160)),
                ('filing_frequency', models.CharField(choices=[('monthly', 'Monthly'), ('semi_monthly', 'Semi Monthly'), ('biweekly', 'Biweekly'), ('weekly', 'Weekly'), ('custom', 'Custom')], default='monthly', max_length=30)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('due_date', models.DateField()),
                ('grace_due_date', models.DateField(blank=True, null=True)),
                ('filing_window_start', models.DateField(blank=True, null=True)),
                ('filing_window_end', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('upcoming', 'Upcoming'), ('due', 'Due'), ('filed', 'Filed'), ('acknowledged', 'Acknowledged'), ('overdue', 'Overdue'), ('waived', 'Waived')], default='upcoming', max_length=20)),
                ('filing_authority_ref', models.CharField(blank=True, max_length=160)),
                ('provider_ref', models.CharField(blank=True, max_length=160)),
                ('output_profile_ref', models.CharField(blank=True, max_length=160)),
                ('source_ref', models.CharField(blank=True, max_length=180)),
                ('source_hash', models.CharField(blank=True, max_length=64)),
                ('config_snapshot', models.JSONField(blank=True, default=dict)),
                ('employer_registration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='filing_calendars', to='payroll.payrollstatutoryemployerregistration')),
                ('statutory_component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='filing_calendars', to='payroll.payrollstatutorycomponent')),
                ('statutory_pack', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='filing_calendars', to='payroll.payrollstatutorypack')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_statutory_filing_calendars', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Payroll Statutory Filing Calendar',
                'verbose_name_plural': 'Payroll Statutory Filing Calendars',
                'ordering': ['due_date', 'statutory_pack__name', 'filing_type_ref'],
                'unique_together': {('tenant', 'code')},
            },
        ),
    ]
