# Generated by Django 5.1.15 on 2026-09-06 01:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0021_payrollstatutoryemployerregistration_and_more'),
        ('tenants', '0002_tenant_onboarding_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollProviderCallbackEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_ref', models.CharField(max_length=160)),
                ('external_reference', models.CharField(blank=True, max_length=180)),
                ('external_event_id', models.CharField(blank=True, max_length=180)),
                ('idempotency_key', models.CharField(max_length=180)),
                ('callback_profile_ref', models.CharField(default='payroll.callback.manual.v1', max_length=160)),
                ('callback_verification_ref', models.CharField(default='payroll.callback.verification.manual.v1', max_length=160)),
                ('status', models.CharField(choices=[('received', 'Received'), ('processed', 'Processed'), ('replayed', 'Replayed'), ('rejected', 'Rejected')], default='received', max_length=20)),
                ('provider_status', models.CharField(choices=[('queued', 'Queued'), ('submitted', 'Submitted'), ('acknowledged', 'Acknowledged'), ('rejected', 'Rejected'), ('failed', 'Failed'), ('reconciled', 'Reconciled')], max_length=20)),
                ('payload_checksum_sha256', models.CharField(max_length=64)),
                ('signature', models.CharField(blank=True, max_length=160)),
                ('verification_snapshot', models.JSONField(blank=True, default=dict)),
                ('payload_snapshot', models.JSONField(blank=True, default=dict)),
                ('processing_snapshot', models.JSONField(blank=True, default=dict)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('failure_code', models.CharField(blank=True, max_length=80)),
                ('failure_reason', models.TextField(blank=True)),
                ('handoff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_callback_events', to='payroll.payrollfinancehandoff')),
                ('output_artifact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='provider_callback_events', to='payroll.payrolloutputartifact')),
                ('provider_delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='callback_events', to='payroll.payrollproviderdelivery')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_provider_callback_events', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Payroll Provider Callback Event',
                'verbose_name_plural': 'Payroll Provider Callback Events',
                'ordering': ['-received_at', '-created_at'],
                'unique_together': {('provider_ref', 'idempotency_key')},
            },
        ),
    ]
