# Generated by Django 5.1.15 on 2026-09-06 01:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0022_payrollprovidercallbackevent'),
        ('tenants', '0002_tenant_onboarding_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollProviderRetryEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('executed', 'Executed'), ('dead_lettered', 'Dead Lettered'), ('skipped', 'Skipped')], default='scheduled', max_length=20)),
                ('retry_policy_ref', models.CharField(default='payroll.delivery.retry.standard.v1', max_length=160)),
                ('failure_taxonomy_ref', models.CharField(default='payroll.delivery.failure_taxonomy.default.v1', max_length=160)),
                ('failure_category_ref', models.CharField(blank=True, max_length=160)),
                ('retry_reason', models.TextField(blank=True)),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('decision_snapshot', models.JSONField(blank=True, default=dict)),
                ('request_snapshot', models.JSONField(blank=True, default=dict)),
                ('response_snapshot', models.JSONField(blank=True, default=dict)),
                ('failure_code', models.CharField(blank=True, max_length=80)),
                ('failure_reason', models.TextField(blank=True)),
                ('executed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executed_payroll_provider_retries', to=settings.AUTH_USER_MODEL)),
                ('handoff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_retry_events', to='payroll.payrollfinancehandoff')),
                ('output_artifact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='provider_retry_events', to='payroll.payrolloutputartifact')),
                ('provider_delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retry_events', to='payroll.payrollproviderdelivery')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_payroll_provider_retries', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_provider_retry_events', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Payroll Provider Retry Event',
                'verbose_name_plural': 'Payroll Provider Retry Events',
                'ordering': ['-scheduled_for', '-created_at'],
            },
        ),
    ]
