# Generated by Django 5.1.15 on 2026-09-06 02:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0023_payrollproviderretryevent'),
        ('tenants', '0002_tenant_onboarding_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollProviderConnection',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_ref', models.CharField(max_length=160)),
                ('provider_name', models.CharField(max_length=160)),
                ('provider_kind', models.CharField(choices=[('bank', 'Bank'), ('accounting', 'Accounting'), ('statutory', 'Statutory'), ('other', 'Other')], default='other', max_length=24)),
                ('environment_ref', models.CharField(default='sandbox', max_length=80)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('configured', 'Configured'), ('sandbox_ready', 'Sandbox Ready'), ('certified', 'Certified'), ('active', 'Active'), ('blocked', 'Blocked'), ('archived', 'Archived')], default='draft', max_length=24)),
                ('adapter_ref', models.CharField(blank=True, max_length=180)),
                ('sandbox_adapter_ref', models.CharField(blank=True, max_length=180)),
                ('channel_ref', models.CharField(blank=True, max_length=180)),
                ('credential_ref', models.CharField(blank=True, max_length=180)),
                ('credential_profile_ref', models.CharField(blank=True, max_length=180)),
                ('credential_required', models.BooleanField(default=False)),
                ('callback_profile_ref', models.CharField(blank=True, max_length=180)),
                ('callback_verification_ref', models.CharField(blank=True, max_length=180)),
                ('retry_policy_ref', models.CharField(blank=True, max_length=180)),
                ('certification_status', models.CharField(choices=[('not_started', 'Not Started'), ('pending', 'Pending'), ('passed', 'Passed'), ('failed', 'Failed'), ('expired', 'Expired')], default='not_started', max_length=24)),
                ('certification_profile_ref', models.CharField(blank=True, max_length=180)),
                ('certified_at', models.DateTimeField(blank=True, null=True)),
                ('last_tested_at', models.DateTimeField(blank=True, null=True)),
                ('readiness_snapshot', models.JSONField(blank=True, default=dict)),
                ('certification_snapshot', models.JSONField(blank=True, default=dict)),
                ('config_snapshot', models.JSONField(blank=True, default=dict)),
                ('certified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certified_payroll_provider_connections', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payroll_provider_connections', to=settings.AUTH_USER_MODEL)),
                ('last_tested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tested_payroll_provider_connections', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_provider_connections', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_payroll_provider_connections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payroll Provider Connection',
                'verbose_name_plural': 'Payroll Provider Connections',
                'ordering': ['provider_kind', 'provider_name', 'provider_ref'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='payroll_pay_tenant__5b1fcd_idx'), models.Index(fields=['tenant', 'provider_kind'], name='payroll_pay_tenant__5e1248_idx'), models.Index(fields=['tenant', 'certification_status'], name='payroll_pay_tenant__dc1dc0_idx')],
                'unique_together': {('tenant', 'provider_ref')},
            },
        ),
    ]
