# Generated by Django 5.1.15 on 2026-09-06 08:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0024_payrollproviderconnection'),
        ('tenants', '0002_tenant_onboarding_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollProviderCertificationRun',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_ref', models.CharField(max_length=160)),
                ('provider_kind', models.CharField(choices=[('bank', 'Bank'), ('accounting', 'Accounting'), ('statutory', 'Statutory'), ('other', 'Other')], default='other', max_length=24)),
                ('environment_ref', models.CharField(default='sandbox', max_length=80)),
                ('run_profile_ref', models.CharField(default='payroll.provider_connection.certification_run.sandbox.v1', max_length=180)),
                ('certification_profile_ref', models.CharField(blank=True, max_length=180)),
                ('scenario_profile_ref', models.CharField(blank=True, max_length=180)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('passed', 'Passed'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='queued', max_length=24)),
                ('scenario_count', models.PositiveIntegerField(default=0)),
                ('passed_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('blocker_count', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('request_snapshot', models.JSONField(blank=True, default=dict)),
                ('response_snapshot', models.JSONField(blank=True, default=dict)),
                ('evidence_snapshot', models.JSONField(blank=True, default=dict)),
                ('error_snapshot', models.JSONField(blank=True, default=dict)),
                ('source_hash', models.CharField(blank=True, max_length=64)),
                ('executed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executed_payroll_provider_certification_runs', to=settings.AUTH_USER_MODEL)),
                ('provider_connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certification_runs', to='payroll.payrollproviderconnection')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_payroll_provider_certification_runs', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_provider_certification_runs', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Payroll Provider Certification Run',
                'verbose_name_plural': 'Payroll Provider Certification Runs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'provider_ref'], name='payroll_pay_tenant__67d8cd_idx'), models.Index(fields=['tenant', 'status'], name='payroll_pay_tenant__144e1d_idx'), models.Index(fields=['tenant', 'provider_kind'], name='payroll_pay_tenant__d22aba_idx')],
            },
        ),
    ]
