# Generated by Django 5.1.15 on 2026-09-06 09:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0025_payrollprovidercertificationrun'),
        ('tenants', '0002_tenant_onboarding_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollProviderJob',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_kind', models.CharField(choices=[('provider_submission', 'Provider Submission'), ('provider_retry', 'Provider Retry'), ('provider_certification', 'Provider Certification'), ('callback_reconciliation', 'Callback Reconciliation')], max_length=40)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('leased', 'Leased'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('dead_lettered', 'Dead Lettered'), ('skipped', 'Skipped'), ('canceled', 'Canceled')], default='queued', max_length=24)),
                ('queue_policy_ref', models.CharField(default='payroll.provider_queue.standard.v1', max_length=180)),
                ('worker_profile_ref', models.CharField(default='payroll.provider_worker.standard.v1', max_length=180)),
                ('idempotency_key', models.CharField(max_length=220)),
                ('provider_ref', models.CharField(blank=True, max_length=160)),
                ('priority', models.PositiveSmallIntegerField(default=100)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=3)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('leased_at', models.DateTimeField(blank=True, null=True)),
                ('leased_until', models.DateTimeField(blank=True, null=True)),
                ('lease_owner_ref', models.CharField(blank=True, max_length=180)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('request_snapshot', models.JSONField(blank=True, default=dict)),
                ('lease_snapshot', models.JSONField(blank=True, default=dict)),
                ('response_snapshot', models.JSONField(blank=True, default=dict)),
                ('failure_code', models.CharField(blank=True, max_length=80)),
                ('failure_reason', models.TextField(blank=True)),
                ('callback_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provider_jobs', to='payroll.payrollprovidercallbackevent')),
                ('certification_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provider_jobs', to='payroll.payrollprovidercertificationrun')),
                ('executed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executed_payroll_provider_jobs', to=settings.AUTH_USER_MODEL)),
                ('provider_connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provider_jobs', to='payroll.payrollproviderconnection')),
                ('provider_delivery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provider_jobs', to='payroll.payrollproviderdelivery')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_payroll_provider_jobs', to=settings.AUTH_USER_MODEL)),
                ('retry_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provider_jobs', to='payroll.payrollproviderretryevent')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_provider_jobs', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Payroll Provider Job',
                'verbose_name_plural': 'Payroll Provider Jobs',
                'ordering': ['scheduled_for', 'priority', 'created_at'],
                'indexes': [models.Index(fields=['tenant', 'status', 'scheduled_for'], name='payroll_pay_tenant__af1fb5_idx'), models.Index(fields=['tenant', 'job_kind', 'status'], name='payroll_pay_tenant__dfc825_idx'), models.Index(fields=['tenant', 'provider_ref'], name='payroll_pay_tenant__5de6d5_idx')],
                'unique_together': {('tenant', 'idempotency_key')},
            },
        ),
    ]
