# Generated by Django 5.1.15 on 2026-09-06 09:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0026_payrollproviderjob'),
        ('tenants', '0002_tenant_onboarding_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollProviderSchemaMappingPack',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_ref', models.CharField(max_length=160)),
                ('provider_kind', models.CharField(choices=[('bank', 'Bank'), ('accounting', 'Accounting'), ('statutory', 'Statutory'), ('other', 'Other')], default='other', max_length=24)),
                ('environment_ref', models.CharField(default='sandbox', max_length=80)),
                ('artifact_kind', models.CharField(choices=[('payslip', 'Payslip'), ('register', 'Register'), ('bank_advice', 'Bank Advice'), ('accounting_export', 'Accounting Export'), ('statutory_report', 'Statutory Report')], max_length=40)),
                ('mapping_profile_ref', models.CharField(max_length=180)),
                ('version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('source_schema_ref', models.CharField(blank=True, max_length=180)),
                ('target_schema_ref', models.CharField(blank=True, max_length=180)),
                ('transform_profile_ref', models.CharField(default='payroll.provider_mapping.transform.safe_paths.v1', max_length=180)),
                ('validation_profile_ref', models.CharField(default='payroll.provider_mapping.validation.standard.v1', max_length=180)),
                ('enforcement_mode', models.CharField(default='warn', max_length=20)),
                ('transform_rules', models.JSONField(blank=True, default=list)),
                ('validation_rules', models.JSONField(blank=True, default=list)),
                ('sample_request_snapshot', models.JSONField(blank=True, default=dict)),
                ('sample_output_snapshot', models.JSONField(blank=True, default=dict)),
                ('evidence_snapshot', models.JSONField(blank=True, default=dict)),
                ('source_hash', models.CharField(blank=True, max_length=64)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payroll_provider_schema_mapping_packs', to=settings.AUTH_USER_MODEL)),
                ('provider_connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schema_mapping_packs', to='payroll.payrollproviderconnection')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_provider_schema_mapping_packs', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_payroll_provider_schema_mapping_packs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payroll Provider Schema Mapping Pack',
                'verbose_name_plural': 'Payroll Provider Schema Mapping Packs',
                'ordering': ['provider_kind', 'provider_ref', 'artifact_kind', '-version'],
                'indexes': [models.Index(fields=['tenant', 'provider_ref', 'artifact_kind', 'status'], name='payroll_pay_tenant__e80354_idx'), models.Index(fields=['tenant', 'mapping_profile_ref', 'status'], name='payroll_pay_tenant__bf441a_idx')],
                'unique_together': {('tenant', 'mapping_profile_ref', 'version')},
            },
        ),
    ]
