# Generated by Django 5.1.15 on 2026-09-06 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0027_payrollproviderschemamappingpack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrollprovidercallbackevent',
            name='signature',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
