# Generated by Django 5.1.15 on 2026-09-06 11:50

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0028_alter_payrollprovidercallbackevent_signature'),
        ('tenants', '0002_tenant_onboarding_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollProviderSchemaMappingSimulation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_ref', models.CharField(max_length=160)),
                ('provider_kind', models.CharField(choices=[('bank', 'Bank'), ('accounting', 'Accounting'), ('statutory', 'Statutory'), ('other', 'Other')], default='other', max_length=24)),
                ('environment_ref', models.CharField(default='sandbox', max_length=80)),
                ('artifact_kind', models.CharField(choices=[('payslip', 'Payslip'), ('register', 'Register'), ('bank_advice', 'Bank Advice'), ('accounting_export', 'Accounting Export'), ('statutory_report', 'Statutory Report')], max_length=40)),
                ('mapping_profile_ref', models.CharField(max_length=180)),
                ('mapping_pack_version', models.PositiveIntegerField(default=1)),
                ('baseline_mapping_pack_version', models.PositiveIntegerField(default=0)),
                ('simulation_profile_ref', models.CharField(default='payroll.provider_schema_mapping_pack.simulation.v1', max_length=180)),
                ('comparison_profile_ref', models.CharField(default='payroll.provider_schema_mapping_pack.comparison.v1', max_length=180)),
                ('status', models.CharField(choices=[('passed', 'Passed'), ('blocked', 'Blocked')], default='blocked', max_length=20)),
                ('comparison_status', models.CharField(default='no_baseline', max_length=24)),
                ('gate_count', models.PositiveIntegerField(default=0)),
                ('passed_gate_count', models.PositiveIntegerField(default=0)),
                ('blocker_count', models.PositiveIntegerField(default=0)),
                ('changed_path_count', models.PositiveIntegerField(default=0)),
                ('added_path_count', models.PositiveIntegerField(default=0)),
                ('removed_path_count', models.PositiveIntegerField(default=0)),
                ('request_snapshot', models.JSONField(blank=True, default=dict)),
                ('provider_payload_snapshot', models.JSONField(blank=True, default=dict)),
                ('baseline_payload_snapshot', models.JSONField(blank=True, default=dict)),
                ('gate_snapshot', models.JSONField(blank=True, default=list)),
                ('blocking_gate_refs', models.JSONField(blank=True, default=list)),
                ('comparison_snapshot', models.JSONField(blank=True, default=dict)),
                ('evidence_snapshot', models.JSONField(blank=True, default=dict)),
                ('source_hash', models.CharField(blank=True, max_length=64)),
                ('simulated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('baseline_mapping_pack', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='baseline_simulation_runs', to='payroll.payrollproviderschemamappingpack')),
                ('mapping_pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulation_runs', to='payroll.payrollproviderschemamappingpack')),
                ('provider_connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schema_mapping_simulations', to='payroll.payrollproviderconnection')),
                ('simulated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_provider_schema_mapping_simulations', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_provider_schema_mapping_simulations', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Payroll Provider Schema Mapping Simulation',
                'verbose_name_plural': 'Payroll Provider Schema Mapping Simulations',
                'ordering': ['-simulated_at', '-created_at'],
                'indexes': [models.Index(fields=['tenant', 'provider_ref', 'artifact_kind', '-simulated_at'], name='payroll_pay_tenant__dbd4c8_idx'), models.Index(fields=['tenant', 'mapping_profile_ref', '-simulated_at'], name='payroll_pay_tenant__c39229_idx'), models.Index(fields=['tenant', 'status', 'comparison_status'], name='payroll_pay_tenant__6a4328_idx')],
            },
        ),
    ]
