# Generated by Django 5.1.15 on 2026-09-06 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0029_payrollproviderschemamappingsimulation'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollproviderjob',
            name='heartbeat_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payrollproviderjob',
            name='heartbeat_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payrollproviderjob',
            name='last_recovered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payrollproviderjob',
            name='recovery_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
