# Generated by Django 5.1.15 on 2026-09-06 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0030_payrollproviderjob_heartbeat_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrolloutputartifact',
            name='kind',
            field=models.CharField(choices=[('payslip', 'Payslip'), ('register', 'Register'), ('bank_advice', 'Bank Advice'), ('accounting_export', 'Accounting Export'), ('statutory_report', 'Statutory Report'), ('provider_audit_pack', 'Provider Audit Pack')], default='payslip', max_length=40),
        ),
        migrations.AlterField(
            model_name='payrollproviderdelivery',
            name='artifact_kind',
            field=models.CharField(choices=[('payslip', 'Payslip'), ('register', 'Register'), ('bank_advice', 'Bank Advice'), ('accounting_export', 'Accounting Export'), ('statutory_report', 'Statutory Report'), ('provider_audit_pack', 'Provider Audit Pack')], max_length=40),
        ),
        migrations.AlterField(
            model_name='payrollproviderschemamappingpack',
            name='artifact_kind',
            field=models.CharField(choices=[('payslip', 'Payslip'), ('register', 'Register'), ('bank_advice', 'Bank Advice'), ('accounting_export', 'Accounting Export'), ('statutory_report', 'Statutory Report'), ('provider_audit_pack', 'Provider Audit Pack')], max_length=40),
        ),
        migrations.AlterField(
            model_name='payrollproviderschemamappingsimulation',
            name='artifact_kind',
            field=models.CharField(choices=[('payslip', 'Payslip'), ('register', 'Register'), ('bank_advice', 'Bank Advice'), ('accounting_export', 'Accounting Export'), ('statutory_report', 'Statutory Report'), ('provider_audit_pack', 'Provider Audit Pack')], max_length=40),
        ),
    ]
