# Generated by Django 5.1.15 on 2026-09-07 04:44

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0031_alter_payrolloutputartifact_kind_and_more'),
        ('tenants', '0002_tenant_onboarding_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollProviderLaunchRehearsal',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rehearsal_profile_ref', models.CharField(default='payroll.provider_launch_rehearsal.v1', max_length=180)),
                ('audit_pack_ref', models.CharField(default='payroll.provider_launch_readiness.audit_pack.v1', max_length=180)),
                ('generated_by_ref', models.CharField(default='payroll.provider_launch_readiness.management_command.v1', max_length=180)),
                ('status', models.CharField(choices=[('ready', 'Ready'), ('blocked', 'Blocked')], default='blocked', max_length=20)),
                ('can_launch', models.BooleanField(default=False)),
                ('ready_lane_count', models.PositiveIntegerField(default=0)),
                ('blocked_lane_count', models.PositiveIntegerField(default=0)),
                ('launch_blocker_count', models.PositiveIntegerField(default=0)),
                ('release_blocker_refs', models.JSONField(blank=True, default=list)),
                ('audit_pack_snapshot', models.JSONField(blank=True, default=dict)),
                ('evidence_checksum_sha256', models.CharField(blank=True, max_length=64)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('source_hash', models.CharField(blank=True, max_length=64)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_payroll_provider_launch_rehearsals', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_provider_launch_rehearsals', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Payroll Provider Launch Rehearsal',
                'verbose_name_plural': 'Payroll Provider Launch Rehearsals',
                'ordering': ['-generated_at', '-created_at'],
                'indexes': [models.Index(fields=['tenant', 'status', 'generated_at'], name='payroll_pay_tenant__da41a5_idx'), models.Index(fields=['tenant', 'can_launch'], name='payroll_pay_tenant__771495_idx'), models.Index(fields=['tenant', 'evidence_checksum_sha256'], name='payroll_pay_tenant__ca22d0_idx')],
            },
        ),
    ]
