# Generated by Django 5.1.15 on 2026-09-10 17:21

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0032_payrollproviderlaunchrehearsal'),
        ('tenants', '0002_tenant_onboarding_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollReportExportAudit',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_membership_ref', models.CharField(blank=True, max_length=120)),
                ('actor_display', models.CharField(blank=True, max_length=180)),
                ('report_key', models.SlugField(max_length=120)),
                ('export_type', models.CharField(choices=[('csv', 'CSV'), ('manifest', 'Manifest')], max_length=20)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('checksum_sha256', models.CharField(max_length=64)),
                ('content_type', models.CharField(max_length=120)),
                ('source_endpoints', models.JSONField(blank=True, default=list)),
                ('evidence_columns', models.JSONField(blank=True, default=list)),
                ('request_identifier', models.CharField(blank=True, max_length=120)),
                ('user_agent', models.TextField(blank=True)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('source_hash', models.CharField(blank=True, max_length=64)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_report_export_audits', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_report_export_audits', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Payroll Report Export Audit',
                'verbose_name_plural': 'Payroll Report Export Audits',
                'ordering': ['-generated_at', '-created_at'],
                'indexes': [models.Index(fields=['tenant', '-generated_at'], name='payroll_pay_tenant__201f99_idx'), models.Index(fields=['tenant', 'report_key', '-generated_at'], name='payroll_pay_tenant__fa4aa0_idx'), models.Index(fields=['tenant', 'export_type', '-generated_at'], name='payroll_pay_tenant__ef5620_idx'), models.Index(fields=['tenant', 'checksum_sha256'], name='payroll_pay_tenant__920935_idx')],
            },
        ),
    ]
