# Generated by Django 5.1.15 on 2026-06-08 17:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leave_management", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LeaveBalanceTransaction",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("action", models.CharField(choices=[("credit_adjustment", "Credit Adjustment"), ("debit_adjustment", "Debit Adjustment"), ("encashment", "Encashment")], max_length=30)),
                ("units", models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ("effective_date", models.DateField()),
                ("reason", models.TextField(blank=True)),
                ("closing_balance_before", models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ("closing_balance_after", models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("employee", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="leave_balance_transactions", to="employees.employee")),
                ("leave_balance", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="transactions", to="leave_management.leavebalance")),
                ("leave_policy", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="leave_balance_transactions", to="leave_management.leavepolicy")),
                ("performed_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="performed_leave_balance_transactions", to="employees.employee")),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="leave_balance_transactions", to="tenants.tenant")),
            ],
            options={
                "verbose_name": "Leave Balance Transaction",
                "verbose_name_plural": "Leave Balance Transactions",
                "ordering": ["-created_at"],
            },
        ),
    ]
