# Generated by Django 5.1.15 on 2026-06-18 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("platform_policies", "0002_tenantpolicypackitemlink"),
        ("leave_management", "0003_leavebalancetransaction_review_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="leavepolicy",
            name="delegation_mode",
            field=models.CharField(blank=True, choices=[("locked", "Locked"), ("tenant_editable", "Tenant Editable"), ("tenant_editable_after_clone", "Tenant Editable After Clone"), ("platform_approval_required", "Platform Approval Required")], max_length=40),
        ),
        migrations.AddField(
            model_name="leavepolicy",
            name="managed_by_platform",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="leavepolicy",
            name="platform_locked_fields",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="leavepolicy",
            name="source_item_key",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="leavepolicy",
            name="source_kind",
            field=models.CharField(choices=[("tenant_native", "Tenant Native"), ("platform_pack", "Platform Pack"), ("tenant_clone", "Tenant Clone")], default="tenant_native", max_length=30),
        ),
        migrations.AddField(
            model_name="leavepolicy",
            name="source_pack_code",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="leavepolicy",
            name="source_version",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="leavetype",
            name="managed_by_platform",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="leavetype",
            name="platform_locked_fields",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="leavetype",
            name="source_item_key",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="leavetype",
            name="source_kind",
            field=models.CharField(choices=[("tenant_native", "Tenant Native"), ("platform_pack", "Platform Pack"), ("tenant_clone", "Tenant Clone")], default="tenant_native", max_length=30),
        ),
        migrations.AddField(
            model_name="leavetype",
            name="source_pack_code",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="leavetype",
            name="source_version",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
