# Generated by Django 5.1.15 on 2026-06-18 00:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("iam", "0001_initial"),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TenantOnboarding",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("owner_mode", models.CharField(choices=[("combined_platform_admin", "Combined Platform Admin"), ("split_platform_roles", "Split Platform Roles")], default="combined_platform_admin", max_length=30)),
                ("setup_style", models.CharField(choices=[("platform_assisted", "Platform Assisted"), ("shared", "Shared"), ("customer_led", "Customer Led")], default="platform_assisted", max_length=30)),
                ("data_setup_style", models.CharField(choices=[("manual", "Manual"), ("import_led", "Import Led"), ("seeded_demo", "Seeded Demo")], default="manual", max_length=30)),
                ("policy_control_style", models.CharField(choices=[("mostly_locked", "Mostly Locked"), ("mostly_delegated", "Mostly Delegated"), ("mixed", "Mixed")], default="mixed", max_length=30)),
                ("country_context", models.CharField(blank=True, max_length=2)),
                ("industry_context", models.CharField(blank=True, max_length=80)),
                ("notes", models.TextField(blank=True)),
                ("internal_handoff_notes", models.TextField(blank=True)),
                ("customer_handoff_notes", models.TextField(blank=True)),
                ("first_login_verified_at", models.DateTimeField(blank=True, null=True)),
                ("baseline_published_at", models.DateTimeField(blank=True, null=True)),
                ("handoff_completed_at", models.DateTimeField(blank=True, null=True)),
                ("tenant", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="onboarding_record", to="tenants.tenant")),
            ],
            options={
                "verbose_name": "Tenant Onboarding",
                "verbose_name_plural": "Tenant Onboarding",
                "ordering": ["tenant__name"],
            },
        ),
        migrations.CreateModel(
            name="TenantOnboardingEvent",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("event_type", models.CharField(max_length=50)),
                ("summary", models.CharField(blank=True, max_length=255)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("actor_identifier", models.CharField(blank=True, max_length=120)),
                ("onboarding", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="events", to="tenant_onboarding.tenantonboarding")),
            ],
            options={
                "verbose_name": "Tenant Onboarding Event",
                "verbose_name_plural": "Tenant Onboarding Events",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TenantOnboardingChecklistItem",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("code", models.CharField(max_length=80)),
                ("label", models.CharField(max_length=255)),
                ("status", models.CharField(choices=[("pending", "Pending"), ("completed", "Completed"), ("skipped", "Skipped")], default="pending", max_length=20)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("completed_by_identifier", models.CharField(blank=True, max_length=120)),
                ("notes", models.TextField(blank=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("onboarding", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="checklist_items", to="tenant_onboarding.tenantonboarding")),
            ],
            options={
                "verbose_name": "Tenant Onboarding Checklist Item",
                "verbose_name_plural": "Tenant Onboarding Checklist Items",
                "ordering": ["sort_order", "label"],
                "unique_together": {("onboarding", "code")},
            },
        ),
        migrations.CreateModel(
            name="TenantOnboardingAdminContact",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("full_name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("phone_number", models.CharField(blank=True, max_length=30)),
                ("job_title", models.CharField(blank=True, max_length=120)),
                ("is_primary", models.BooleanField(default=False)),
                ("provisioning_status", models.CharField(choices=[("planned", "Planned"), ("provisioned", "Provisioned"), ("invited", "Invited"), ("activated", "Activated"), ("superseded", "Superseded")], default="planned", max_length=20)),
                ("invited_at", models.DateTimeField(blank=True, null=True)),
                ("first_login_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("membership", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="tenant_onboarding_contacts", to="iam.tenantmembership")),
                ("onboarding", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="admin_contacts", to="tenant_onboarding.tenantonboarding")),
                ("user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="tenant_onboarding_contacts", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Tenant Onboarding Admin Contact",
                "verbose_name_plural": "Tenant Onboarding Admin Contacts",
                "ordering": ["-is_primary", "full_name"],
            },
        ),
    ]
