# Generated by Django 5.1.15 on 2026-09-14 01:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_onboarding', '0001_initial'),
        ('tenants', '0002_tenant_onboarding_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicTenantLead',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('intent', models.CharField(choices=[('signup', 'Signup'), ('contact', 'Contact')], default='signup', max_length=20)),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewing', 'Reviewing'), ('qualified', 'Qualified'), ('converted', 'Converted'), ('closed', 'Closed')], default='new', max_length=20)),
                ('company_name', models.CharField(max_length=255)),
                ('contact_name', models.CharField(max_length=255)),
                ('work_email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=30)),
                ('employee_count', models.PositiveIntegerField(blank=True, null=True)),
                ('industry', models.CharField(blank=True, max_length=80)),
                ('country_code', models.CharField(default='IN', max_length=2)),
                ('preferred_plan', models.CharField(blank=True, max_length=40)),
                ('message', models.TextField(blank=True)),
                ('source_path', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('reviewed_by_identifier', models.CharField(blank=True, max_length=120)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('converted_tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='public_leads', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Public Tenant Lead',
                'verbose_name_plural': 'Public Tenant Leads',
                'ordering': ['-created_at'],
            },
        ),
    ]
