# Generated by Django 5.1.15 on 2026-10-04 05:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_onboarding', '0002_publictenantlead'),
        ('tenants', '0002_tenant_onboarding_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantonboarding',
            name='launch_applied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenantonboarding',
            name='launch_blueprint_ref',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='tenantonboarding',
            name='launch_blueprint_version',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='tenantonboarding',
            name='launch_preview_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='tenantonboarding',
            name='launch_readiness_status',
            field=models.CharField(choices=[('not_configured', 'Not Configured'), ('configured', 'Configured'), ('stage_ready', 'Stage Ready'), ('customer_ready', 'Customer Ready'), ('payroll_rehearsal_ready', 'Payroll Rehearsal Ready'), ('production_ready', 'Production Ready'), ('blocked', 'Blocked')], default='not_configured', max_length=40),
        ),
        migrations.AddField(
            model_name='tenantonboarding',
            name='launch_selected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenantonboarding',
            name='launch_status_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tenantonboarding',
            name='launch_subscription_plan_snapshot',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='tenantonboarding',
            name='launch_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='TenantLaunchRun',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('blueprint_ref', models.CharField(max_length=120)),
                ('blueprint_version', models.CharField(max_length=40)),
                ('subscription_plan', models.CharField(max_length=40)),
                ('run_type', models.CharField(choices=[('preview', 'Preview'), ('apply', 'Apply'), ('verify', 'Verify'), ('repair', 'Repair'), ('upgrade', 'Upgrade')], default='preview', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('requested_by_identifier', models.CharField(blank=True, max_length=120)),
                ('idempotency_key', models.CharField(blank=True, max_length=120)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('input_payload', models.JSONField(blank=True, default=dict)),
                ('plan_snapshot', models.JSONField(blank=True, default=dict)),
                ('result_payload', models.JSONField(blank=True, default=dict)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('onboarding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='launch_runs', to='tenant_onboarding.tenantonboarding')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='launch_runs', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Tenant Launch Run',
                'verbose_name_plural': 'Tenant Launch Runs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TenantLaunchSeededItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_key', models.CharField(max_length=180)),
                ('item_kind', models.CharField(max_length=80)),
                ('module_ref', models.CharField(max_length=80)),
                ('action', models.CharField(choices=[('plan', 'Plan'), ('create', 'Create'), ('update', 'Update'), ('skip', 'Skip'), ('noop', 'No-op'), ('block', 'Block')], default='plan', max_length=20)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('succeeded', 'Succeeded'), ('skipped', 'Skipped'), ('blocked', 'Blocked'), ('failed', 'Failed')], default='planned', max_length=20)),
                ('ownership_mode', models.CharField(blank=True, max_length=40)),
                ('object_ref', models.CharField(blank=True, max_length=180)),
                ('checksum_sha256', models.CharField(blank=True, max_length=64)),
                ('message', models.CharField(blank=True, max_length=255)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('launch_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seeded_items', to='tenant_onboarding.tenantlaunchrun')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='launch_seeded_items', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Tenant Launch Seeded Item',
                'verbose_name_plural': 'Tenant Launch Seeded Items',
                'ordering': ['module_ref', 'item_kind', 'item_key'],
            },
        ),
        migrations.AddIndex(
            model_name='tenantlaunchrun',
            index=models.Index(fields=['tenant', 'run_type', 'status'], name='tenant_onbo_tenant__1c9233_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantlaunchrun',
            index=models.Index(fields=['tenant', 'blueprint_ref', 'blueprint_version'], name='tenant_onbo_tenant__62cbbf_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantlaunchrun',
            index=models.Index(fields=['tenant', 'idempotency_key'], name='tenant_onbo_tenant__1b7585_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantlaunchseededitem',
            index=models.Index(fields=['tenant', 'module_ref', 'status'], name='tenant_onbo_tenant__6ec15a_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantlaunchseededitem',
            index=models.Index(fields=['tenant', 'item_kind'], name='tenant_onbo_tenant__202d67_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantlaunchseededitem',
            index=models.Index(fields=['tenant', 'object_ref'], name='tenant_onbo_tenant__1f472c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tenantlaunchseededitem',
            unique_together={('launch_run', 'item_key')},
        ),
    ]
