# Generated by Django 5.1.15 on 2026-06-06 17:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationDefinition',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=120, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('organization', 'Organization'), ('employee', 'Employee'), ('lifecycle', 'Lifecycle'), ('leave', 'Leave'), ('attendance', 'Attendance'), ('workflow', 'Workflow'), ('notification', 'Notification'), ('reporting', 'Reporting'), ('document', 'Document'), ('security', 'Security')], max_length=30)),
                ('data_type', models.CharField(choices=[('string', 'String'), ('integer', 'Integer'), ('boolean', 'Boolean'), ('decimal', 'Decimal'), ('json', 'JSON'), ('array', 'Array')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('default_value', models.JSONField(blank=True, default=dict)),
                ('validation_schema', models.JSONField(blank=True, default=dict)),
                ('is_scoped', models.BooleanField(default=True)),
                ('is_sensitive', models.BooleanField(default=False)),
                ('is_system_managed', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Configuration Definition',
                'verbose_name_plural': 'Configuration Definitions',
                'ordering': ['category', 'key'],
            },
        ),
        migrations.CreateModel(
            name='SeedPackTemplate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(choices=[('standard_office', 'Standard Office'), ('shift_based', 'Shift Based Operations'), ('retail_field', 'Retail or Field Workforce'), ('professional_services', 'Professional Services')], max_length=60, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Seed Pack Template',
                'verbose_name_plural': 'Seed Pack Templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ConfigurationChangeLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=50)),
                ('summary', models.CharField(blank=True, max_length=255)),
                ('before_value', models.JSONField(blank=True, default=dict)),
                ('after_value', models.JSONField(blank=True, default=dict)),
                ('scope_type', models.CharField(choices=[('tenant', 'Tenant'), ('legal_entity', 'Legal Entity'), ('branch', 'Branch'), ('department', 'Department'), ('grade', 'Grade'), ('employment_type', 'Employment Type'), ('employee', 'Employee')], default='tenant', max_length=30)),
                ('actor_identifier', models.CharField(blank=True, max_length=120)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuration_change_logs', to='tenants.tenant')),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='platform_config.configurationdefinition')),
            ],
            options={
                'verbose_name': 'Configuration Change Log',
                'verbose_name_plural': 'Configuration Change Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TenantConfiguration',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('current_value', models.JSONField(blank=True, default=dict)),
                ('published_value', models.JSONField(blank=True, default=dict)),
                ('version', models.PositiveIntegerField(default=1)),
                ('effective_from', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('published_by_note', models.CharField(blank=True, max_length=255)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_configurations', to='platform_config.configurationdefinition')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configurations', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Tenant Configuration',
                'verbose_name_plural': 'Tenant Configurations',
                'ordering': ['tenant', 'definition__key'],
                'unique_together': {('tenant', 'definition')},
            },
        ),
        migrations.CreateModel(
            name='ScopedConfigurationOverride',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope_type', models.CharField(choices=[('tenant', 'Tenant'), ('legal_entity', 'Legal Entity'), ('branch', 'Branch'), ('department', 'Department'), ('grade', 'Grade'), ('employment_type', 'Employment Type'), ('employee', 'Employee')], max_length=30)),
                ('employee_identifier', models.CharField(blank=True, max_length=120)),
                ('override_value', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('effective_from', models.DateTimeField(blank=True, null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='config_overrides', to='organizations.branch')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='config_overrides', to='organizations.department')),
                ('employment_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='config_overrides', to='organizations.employmenttype')),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='config_overrides', to='organizations.grade')),
                ('legal_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='config_overrides', to='organizations.legalentity')),
                ('tenant_configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overrides', to='platform_config.tenantconfiguration')),
            ],
            options={
                'verbose_name': 'Scoped Configuration Override',
                'verbose_name_plural': 'Scoped Configuration Overrides',
                'ordering': ['tenant_configuration', 'scope_type', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='SeedPackItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.JSONField(blank=True, default=dict)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seed_items', to='platform_config.configurationdefinition')),
                ('seed_pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='platform_config.seedpacktemplate')),
            ],
            options={
                'verbose_name': 'Seed Pack Item',
                'verbose_name_plural': 'Seed Pack Items',
                'ordering': ['seed_pack', 'sort_order', 'definition__key'],
                'unique_together': {('seed_pack', 'definition')},
            },
        ),
    ]
