# Generated by Django 5.1.15 on 2026-09-17 14:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionCatalogEntry',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=120, unique=True)),
                ('label', models.CharField(max_length=255)),
                ('module', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('tenant_assignable', models.BooleanField(default=True)),
                ('required_module', models.CharField(blank=True, max_length=120)),
                ('required_plan', models.CharField(blank=True, max_length=120)),
                ('default_role_codes', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('managed_by_platform', models.BooleanField(default=True)),
                ('source_ref', models.CharField(blank=True, default='code_catalog', max_length=120)),
            ],
            options={
                'verbose_name': 'Permission Catalog Entry',
                'verbose_name_plural': 'Permission Catalog Entries',
                'ordering': ['module', 'key'],
            },
        ),
    ]
