# Generated by Django 5.1.15 on 2026-09-17 15:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0002_permissioncatalogentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuCatalogEntry',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace', models.CharField(max_length=80)),
                ('group', models.CharField(blank=True, max_length=120)),
                ('kind', models.CharField(choices=[('sidebar', 'Sidebar'), ('quick_link', 'Quick Link')], default='sidebar', max_length=20)),
                ('href', models.CharField(max_length=255)),
                ('label', models.CharField(max_length=120)),
                ('short_label', models.CharField(blank=True, max_length=12)),
                ('blurb', models.CharField(blank=True, max_length=255)),
                ('permission_keys', models.JSONField(blank=True, default=list)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('source_ref', models.CharField(blank=True, default='code_catalog', max_length=120)),
            ],
            options={
                'verbose_name': 'Menu Catalog Entry',
                'verbose_name_plural': 'Menu Catalog Entries',
                'ordering': ['workspace', 'kind', 'group', 'sort_order', 'label'],
                'unique_together': {('workspace', 'kind', 'href')},
            },
        ),
    ]
