# Generated by Django 5.1.15 on 2026-06-06 17:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0002_initial'),
        ('organizations', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=60)),
                ('name', models.CharField(max_length=255)),
                ('category_type', models.CharField(choices=[('identity', 'Identity'), ('address', 'Address'), ('education', 'Education'), ('experience', 'Experience'), ('bank', 'Bank'), ('tax', 'Tax'), ('contract', 'Contract'), ('policy', 'Policy'), ('medical', 'Medical'), ('other', 'Other')], default='other', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_system_seeded', models.BooleanField(default=False)),
                ('requires_expiry_date', models.BooleanField(default=False)),
                ('requires_verification', models.BooleanField(default=True)),
                ('allow_employee_upload', models.BooleanField(default=True)),
                ('allow_multiple_files', models.BooleanField(default=False)),
                ('visibility_rules', models.JSONField(blank=True, default=dict)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_categories', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Document Category',
                'verbose_name_plural': 'Document Categories',
                'ordering': ['name'],
                'unique_together': {('tenant', 'code')},
            },
        ),
        migrations.CreateModel(
            name='DocumentRequirementRule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('required_within_days_of_joining', models.PositiveIntegerField(default=0)),
                ('priority', models.PositiveIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_requirement_rules', to='organizations.branch')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirement_rules', to='documents.documentcategory')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_requirement_rules', to='organizations.department')),
                ('employment_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_requirement_rules', to='organizations.employmenttype')),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_requirement_rules', to='organizations.grade')),
                ('legal_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_requirement_rules', to='organizations.legalentity')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_requirement_rules', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Document Requirement Rule',
                'verbose_name_plural': 'Document Requirement Rules',
                'ordering': ['priority', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('replaced', 'Replaced')], default='active', max_length=20)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('file_name', models.CharField(max_length=255)),
                ('file_url', models.URLField(blank=True)),
                ('file_path', models.CharField(blank=True, max_length=512)),
                ('mime_type', models.CharField(blank=True, max_length=120)),
                ('file_size_bytes', models.PositiveBigIntegerField(default=0)),
                ('document_number', models.CharField(blank=True, max_length=120)),
                ('issued_on', models.DateField(blank=True, null=True)),
                ('expires_on', models.DateField(blank=True, null=True)),
                ('uploaded_by_identifier', models.CharField(blank=True, max_length=120)),
                ('verified_by_identifier', models.CharField(blank=True, max_length=120)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_documents', to='documents.documentcategory')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='employees.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_documents', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Employee Document',
                'verbose_name_plural': 'Employee Documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentVerificationLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('previous_status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('expired', 'Expired')], max_length=20)),
                ('new_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('expired', 'Expired')], max_length=20)),
                ('actor_identifier', models.CharField(blank=True, max_length=120)),
                ('comment', models.TextField(blank=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_verification_logs', to='tenants.tenant')),
                ('employee_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_logs', to='documents.employeedocument')),
            ],
            options={
                'verbose_name': 'Document Verification Log',
                'verbose_name_plural': 'Document Verification Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedLetter',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('letter_type', models.CharField(choices=[('offer', 'Offer Letter'), ('appointment', 'Appointment Letter'), ('confirmation', 'Confirmation Letter'), ('transfer', 'Transfer Letter'), ('promotion', 'Promotion Letter'), ('relieving', 'Relieving Letter'), ('experience', 'Experience Letter'), ('other', 'Other')], default='other', max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('template_code', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('replaced', 'Replaced')], default='active', max_length=20)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('file_url', models.URLField(blank=True)),
                ('file_path', models.CharField(blank=True, max_length=512)),
                ('workflow_reference', models.CharField(blank=True, max_length=120)),
                ('payload_snapshot', models.JSONField(blank=True, default=dict)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_letters', to='employees.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_letters', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Generated Letter',
                'verbose_name_plural': 'Generated Letters',
                'ordering': ['-created_at'],
            },
        ),
    ]
