# Generated by Django 5.1.15 on 2026-06-19 08:28

import apps.documents.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        ('employees', '0002_initial'),
        ('tenants', '0002_tenant_onboarding_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentArtifact',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_kind', models.CharField(choices=[('uploaded', 'Uploaded'), ('generated', 'Generated')], default='uploaded', max_length=20)),
                ('storage_provider', models.CharField(choices=[('local', 'Local'), ('s3_compatible', 'S3 Compatible'), ('other', 'Other')], default='local', max_length=30)),
                ('original_filename', models.CharField(max_length=255)),
                ('stored_file', models.FileField(max_length=512, upload_to=apps.documents.models.document_artifact_upload_to)),
                ('storage_key', models.CharField(blank=True, max_length=512)),
                ('mime_type', models.CharField(blank=True, max_length=120)),
                ('file_size_bytes', models.PositiveBigIntegerField(default=0)),
                ('checksum_sha256', models.CharField(blank=True, max_length=64)),
                ('created_by_identifier', models.CharField(blank=True, max_length=120)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_artifacts', to='employees.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_artifacts', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Document Artifact',
                'verbose_name_plural': 'Document Artifacts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='artifact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_documents', to='documents.documentartifact'),
        ),
        migrations.AddField(
            model_name='generatedletter',
            name='artifact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_letters', to='documents.documentartifact'),
        ),
    ]
