# Generated by Django 5.1.15 on 2026-06-19 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_documentartifact_employeedocument_artifact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedocument',
            name='previous_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replacement_versions', to='documents.employeedocument'),
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='reupload_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='reupload_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='reupload_requested_by_identifier',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='version_number',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
