from django.urls import path

from apps.tenant_onboarding.api_views import (
    PlatformAdminContactProvisionView,
    PlatformAdminContactDetailView,
    PlatformLaunchBlueprintDetailView,
    PlatformLaunchBlueprintListView,
    PlatformPermissionCatalogDetailView,
    PlatformPermissionCatalogListView,
    PlatformPublicLeadConvertView,
    PlatformPublicLeadDetailView,
    PlatformPublicLeadListView,
    PlatformSummaryView,
    PlatformTenantActivateView,
    PlatformTenantAdminContactCreateView,
    PlatformTenantDetailView,
    PlatformTenantLaunchApplyView,
    PlatformTenantLaunchCertificationReportView,
    PlatformTenantLaunchDriftCheckView,
    PlatformTenantLaunchHandoffView,
    PlatformTenantLaunchPreviewView,
    PlatformTenantLaunchRepairApplyView,
    PlatformTenantLaunchRepairPreviewView,
    PlatformTenantLaunchUpgradeApplyView,
    PlatformTenantLaunchUpgradeCompareView,
    PlatformTenantLaunchRunListView,
    PlatformTenantListCreateView,
    PlatformTenantMarkBaselinePublishedView,
    PlatformTenantMarkHandoffReadyView,
    PlatformTenantOnboardingDetailView,
    PublicTenantLeadCreateView,
)


urlpatterns = [
    path("public-leads/", PublicTenantLeadCreateView.as_view(), name="public-tenant-lead-create"),
    path("permission-catalog/", PlatformPermissionCatalogListView.as_view(), name="platform-permission-catalog-list"),
    path("permission-catalog/<str:permission_key>/", PlatformPermissionCatalogDetailView.as_view(), name="platform-permission-catalog-detail"),
    path("launch-blueprints/", PlatformLaunchBlueprintListView.as_view(), name="platform-launch-blueprint-list"),
    path("launch-blueprints/<str:blueprint_ref>/", PlatformLaunchBlueprintDetailView.as_view(), name="platform-launch-blueprint-detail"),
    path("summary/", PlatformSummaryView.as_view(), name="platform-summary"),
    path("leads/", PlatformPublicLeadListView.as_view(), name="platform-public-lead-list"),
    path("leads/<uuid:item_id>/", PlatformPublicLeadDetailView.as_view(), name="platform-public-lead-detail"),
    path("leads/<uuid:item_id>/convert/", PlatformPublicLeadConvertView.as_view(), name="platform-public-lead-convert"),
    path("tenants/", PlatformTenantListCreateView.as_view(), name="platform-tenant-list-create"),
    path("tenants/<uuid:item_id>/", PlatformTenantDetailView.as_view(), name="platform-tenant-detail"),
    path("tenants/<uuid:item_id>/onboarding/", PlatformTenantOnboardingDetailView.as_view(), name="platform-tenant-onboarding-detail"),
    path("tenants/<uuid:item_id>/launch-runs/", PlatformTenantLaunchRunListView.as_view(), name="platform-tenant-launch-run-list"),
    path("tenants/<uuid:item_id>/launch-certification-report/", PlatformTenantLaunchCertificationReportView.as_view(), name="platform-tenant-launch-certification-report"),
    path("tenants/<uuid:item_id>/launch-preview/", PlatformTenantLaunchPreviewView.as_view(), name="platform-tenant-launch-preview"),
    path("tenants/<uuid:item_id>/launch-apply/", PlatformTenantLaunchApplyView.as_view(), name="platform-tenant-launch-apply"),
    path("tenants/<uuid:item_id>/launch-drift-check/", PlatformTenantLaunchDriftCheckView.as_view(), name="platform-tenant-launch-drift-check"),
    path("tenants/<uuid:item_id>/launch-repair-preview/", PlatformTenantLaunchRepairPreviewView.as_view(), name="platform-tenant-launch-repair-preview"),
    path("tenants/<uuid:item_id>/launch-repair-apply/", PlatformTenantLaunchRepairApplyView.as_view(), name="platform-tenant-launch-repair-apply"),
    path("tenants/<uuid:item_id>/launch-upgrade-compare/", PlatformTenantLaunchUpgradeCompareView.as_view(), name="platform-tenant-launch-upgrade-compare"),
    path("tenants/<uuid:item_id>/launch-upgrade-apply/", PlatformTenantLaunchUpgradeApplyView.as_view(), name="platform-tenant-launch-upgrade-apply"),
    path("tenants/<uuid:item_id>/launch-handoff/", PlatformTenantLaunchHandoffView.as_view(), name="platform-tenant-launch-handoff"),
    path("tenants/<uuid:item_id>/admin-contacts/", PlatformTenantAdminContactCreateView.as_view(), name="platform-tenant-admin-contact-create"),
    path("tenants/<uuid:item_id>/onboarding/mark-baseline-published/", PlatformTenantMarkBaselinePublishedView.as_view(), name="platform-tenant-mark-baseline-published"),
    path("tenants/<uuid:item_id>/onboarding/mark-handoff-ready/", PlatformTenantMarkHandoffReadyView.as_view(), name="platform-tenant-mark-handoff-ready"),
    path("tenants/<uuid:item_id>/onboarding/activate/", PlatformTenantActivateView.as_view(), name="platform-tenant-activate"),
    path("admin-contacts/<uuid:contact_id>/", PlatformAdminContactDetailView.as_view(), name="platform-admin-contact-detail"),
    path("admin-contacts/<uuid:contact_id>/provision-user/", PlatformAdminContactProvisionView.as_view(), name="platform-admin-contact-provision-user"),
]
