# Generated by Django 5.1.15 on 2026-06-06 17:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('legal_name', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('suspended', 'Suspended'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('subscription_plan', models.CharField(choices=[('starter', 'Starter'), ('growth', 'Growth'), ('enterprise', 'Enterprise')], default='starter', max_length=20)),
                ('seed_pack', models.CharField(choices=[('standard_office', 'Standard Office'), ('shift_based', 'Shift Based Operations'), ('retail_field', 'Retail or Field Workforce'), ('professional_services', 'Professional Services')], default='standard_office', max_length=40)),
                ('primary_email', models.EmailField(blank=True, max_length=254)),
                ('primary_phone', models.CharField(blank=True, max_length=30)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('country_code', models.CharField(default='IN', max_length=2)),
                ('is_sandbox', models.BooleanField(default=False)),
                ('go_live_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tenant',
                'verbose_name_plural': 'Tenants',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TenantDomain',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('domain', models.CharField(max_length=255, unique=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Tenant Domain',
                'verbose_name_plural': 'Tenant Domains',
                'ordering': ['domain'],
            },
        ),
    ]
