# Generated by Django 5.1.15 on 2026-06-18 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="activated_by_identifier",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="tenant",
            name="onboarding_completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tenant",
            name="onboarding_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tenant",
            name="onboarding_status",
            field=models.CharField(choices=[("draft", "Draft"), ("created", "Created"), ("prepared", "Prepared"), ("baseline_published", "Baseline Published"), ("handoff_ready", "Handoff Ready"), ("active", "Active")], default="draft", max_length=30),
        ),
        migrations.AddField(
            model_name="tenant",
            name="prepared_by_identifier",
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
