# Generated by Django 5.1.15 on 2026-06-18 00:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0002_tenant_onboarding_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlatformPolicyPack",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("code", models.SlugField(max_length=80, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("domain", models.CharField(choices=[("leave", "Leave"), ("attendance", "Attendance"), ("workflow", "Workflow"), ("document", "Document")], max_length=30)),
                ("country_code", models.CharField(blank=True, max_length=2)),
                ("industry_tag", models.CharField(blank=True, max_length=80)),
                ("description", models.TextField(blank=True)),
                ("status", models.CharField(choices=[("draft", "Draft"), ("published", "Published"), ("archived", "Archived")], default="draft", max_length=20)),
                ("version", models.PositiveIntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("published_by_identifier", models.CharField(blank=True, max_length=120)),
            ],
            options={
                "verbose_name": "Platform Policy Pack",
                "verbose_name_plural": "Platform Policy Packs",
                "ordering": ["domain", "name"],
                "indexes": [models.Index(fields=["domain", "status", "is_active"], name="platform_po_domain_b2d366_idx")],
            },
        ),
        migrations.CreateModel(
            name="PlatformPolicyPackItem",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("item_type", models.CharField(choices=[("leave_type", "Leave Type"), ("leave_policy", "Leave Policy"), ("leave_policy_assignment_rule", "Leave Policy Assignment Rule"), ("shift", "Shift"), ("holiday_calendar", "Holiday Calendar"), ("attendance_policy", "Attendance Policy"), ("attendance_policy_assignment_rule", "Attendance Policy Assignment Rule")], max_length=50)),
                ("item_key", models.CharField(max_length=120)),
                ("name", models.CharField(blank=True, max_length=255)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("dependency_keys", models.JSONField(blank=True, default=list)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_required", models.BooleanField(default=True)),
                ("policy_pack", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="items", to="platform_policies.platformpolicypack")),
            ],
            options={
                "verbose_name": "Platform Policy Pack Item",
                "verbose_name_plural": "Platform Policy Pack Items",
                "ordering": ["policy_pack", "sort_order", "item_key"],
                "indexes": [models.Index(fields=["item_type", "sort_order"], name="platform_po_item_ty_9ae1b3_idx")],
                "unique_together": {("policy_pack", "item_key")},
            },
        ),
        migrations.CreateModel(
            name="PlatformPolicyDelegationRule",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("item_key", models.CharField(blank=True, max_length=120)),
                ("delegation_mode", models.CharField(choices=[("locked", "Locked"), ("tenant_editable", "Tenant Editable"), ("tenant_editable_after_clone", "Tenant Editable After Clone"), ("platform_approval_required", "Platform Approval Required")], max_length=40)),
                ("editable_paths", models.JSONField(blank=True, default=list)),
                ("locked_paths", models.JSONField(blank=True, default=list)),
                ("notes", models.TextField(blank=True)),
                ("policy_pack", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="delegation_rules", to="platform_policies.platformpolicypack")),
            ],
            options={
                "verbose_name": "Platform Policy Delegation Rule",
                "verbose_name_plural": "Platform Policy Delegation Rules",
                "ordering": ["policy_pack", "item_key"],
                "unique_together": {("policy_pack", "item_key")},
            },
        ),
        migrations.CreateModel(
            name="TenantPolicyPackAdoption",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("status", models.CharField(choices=[("draft", "Draft"), ("adopted", "Adopted"), ("superseded", "Superseded")], default="draft", max_length=20)),
                ("adoption_mode", models.CharField(choices=[("baseline_only", "Baseline Only"), ("baseline_plus_tenant_overrides", "Baseline Plus Tenant Overrides"), ("clone_to_tenant_records", "Clone To Tenant Records")], default="clone_to_tenant_records", max_length=40)),
                ("adopted_at", models.DateTimeField(blank=True, null=True)),
                ("adopted_by_identifier", models.CharField(blank=True, max_length=120)),
                ("notes", models.TextField(blank=True)),
                ("policy_pack", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="tenant_adoptions", to="platform_policies.platformpolicypack")),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="policy_pack_adoptions", to="tenants.tenant")),
            ],
            options={
                "verbose_name": "Tenant Policy Pack Adoption",
                "verbose_name_plural": "Tenant Policy Pack Adoptions",
                "ordering": ["tenant__name", "-created_at"],
                "indexes": [models.Index(fields=["tenant", "status"], name="platform_po_tenant__50df1b_idx")],
            },
        ),
    ]
