# Generated by Django 5.1.15 on 2026-06-18 00:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("platform_policies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TenantPolicyPackItemLink",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("target_model", models.CharField(max_length=120)),
                ("target_record_id", models.UUIDField()),
                ("source_version", models.PositiveIntegerField(default=1)),
                ("is_detached_from_source", models.BooleanField(default=False)),
                ("platform_item", models.ForeignKey(on_delete=models.deletion.CASCADE, related_name="tenant_links", to="platform_policies.platformpolicypackitem")),
                ("tenant_adoption", models.ForeignKey(on_delete=models.deletion.CASCADE, related_name="item_links", to="platform_policies.tenantpolicypackadoption")),
            ],
            options={
                "verbose_name": "Tenant Policy Pack Item Link",
                "verbose_name_plural": "Tenant Policy Pack Item Links",
                "ordering": ["tenant_adoption", "platform_item__sort_order", "target_model"],
                "indexes": [models.Index(fields=["target_model", "target_record_id"], name="platform_po_target__b7bcc3_idx")],
                "unique_together": {("tenant_adoption", "platform_item", "target_model", "target_record_id")},
            },
        ),
    ]
