# Generated by Codex on 2026-09-18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("platform_policies", "0002_tenantpolicypackitemlink"),
    ]

    operations = [
        migrations.AddField(
            model_name="platformpolicypack",
            name="source_pack",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="derived_versions",
                to="platform_policies.platformpolicypack",
            ),
        ),
    ]
