import { expect, test } from "@playwright/test";

import { expectNoHorizontalOverflow, expectPageReady } from "../helpers/assertions";

test.describe("HR admin payroll provider connection flows", () => {
  test("provider workspace exposes SaaS onboarding refs, readiness gates, and certification state", async ({ page }) => {
    await page.goto("/hr-admin/payroll-providers");
    await expectPageReady(page, "Payroll Providers");

    await expect(page.getByRole("heading", { name: "Connections" })).toBeVisible();
    await expect(page.getByRole("heading", { name: "Bank payout sandbox" }).first()).toBeVisible();
    await expect(page.getByRole("heading", { name: "Certification checklist" })).toBeVisible();
    await expect(page.getByRole("button", { name: "Run certification" })).toBeVisible();
    await expect(page.getByRole("heading", { name: "Scenario evidence" })).toBeVisible();
    await expect(page.getByText("Adapter contract").first()).toBeVisible();
    await expect(page.getByText("Schema mapping").first()).toBeVisible();
    await expect(page.getByText("Mapping packs").first()).toBeVisible();
    await expect(page.getByText("Provider schema coverage").first()).toBeVisible();
    await expect(page.getByText("Simulation ledger").first()).toBeVisible();
    await expect(page.getByText("Active comparison evidence").first()).toBeVisible();
    await expect(page.getByText("Live adapter readiness").first()).toBeVisible();
    await expect(page.getByText("Launch rehearsal").first()).toBeVisible();
    await expect(page.getByRole("button", { name: "Run rehearsal" })).toBeVisible();
    await expect(page.getByText("Recorded rehearsals").first()).toBeVisible();
    await expect(page.getByText("payroll.provider_launch_readiness.audit_pack.v1").first()).toBeVisible();
    await expect(page.getByText("payroll.provider_launch_rehearsal.v1").first()).toBeVisible();
    await expect(page.getByText("Finance handoff gate").first()).toBeVisible();
    await expect(page.getByText("payroll.provider_adapter.bank.production_pack.v1").first()).toBeVisible();
    await expect(page.getByText("payroll.provider_adapter.bank.live_payout.v1").first()).toBeVisible();
    await expect(page.getByText("payroll.provider_adapter.accounting.live_journal.v1").first()).toBeVisible();
    await expect(page.getByText("payroll.provider_adapter.statutory.live_filing.v1").first()).toBeVisible();
    await expect(page.getByText("payroll.provider_adapter.http_json.v1").first()).toBeVisible();
    await expect(page.getByText("tenant.bank.live-sdk.adapter.v1").first()).toBeVisible();
    await expect(page.getByText("settings.PAYROLL_PROVIDER_ADAPTERS").first()).toBeVisible();
    await expect(page.getByText("Provider client readiness").first()).toBeVisible();
    await expect(page.getByText("payroll.provider_client.bank.fixture.v1").first()).toBeVisible();
    await expect(page.getByText("payroll.provider_client.accounting.fixture.v1").first()).toBeVisible();
    await expect(page.getByText("payroll.provider_client.statutory.fixture.v1").first()).toBeVisible();
    await expect(page.getByText("payroll.provider_client.bank.sdk_http.v1").first()).toBeVisible();
    await expect(page.getByText("payroll.provider_client.bank.razorpayx_http.v1").first()).toBeVisible();
    await expect(page.getByText("payroll.provider_client.accounting.sdk_http.v1").first()).toBeVisible();
    await expect(page.getByText("payroll.provider_client.accounting.tallyprime_http.v1").first()).toBeVisible();
    await expect(page.getByText("payroll.provider_client.statutory.sdk_http.v1").first()).toBeVisible();
    await expect(page.getByText("payroll.provider_client.statutory.epfo_ecr_http.v1").first()).toBeVisible();
    await expect(page.getByText("tenant.bank.live-sdk.client.v1").first()).toBeVisible();
    await expect(page.getByText("settings.PAYROLL_BANK_PAYOUT_CLIENTS").first()).toBeVisible();
    await expect(page.getByText("Certification fixture").first()).toBeVisible();
    await expect(page.getByText("Provider package manifests").first()).toBeVisible();
    await expect(page.getByText("payroll.provider_package.bank.fixture.v1").first()).toBeVisible();
    await expect(page.getByText("payroll.provider_package.accounting.fixture.v1").first()).toBeVisible();
    await expect(page.getByText("payroll.provider_package.statutory.fixture.v1").first()).toBeVisible();
    await expect(page.getByText("payroll.provider_package.bank.sdk_http.v1").first()).toBeVisible();
    await expect(page.getByText("payroll.provider_package.bank.razorpayx_http.v1").first()).toBeVisible();
    await expect(page.getByText("payroll.provider_package.accounting.sdk_http.v1").first()).toBeVisible();
    await expect(page.getByText("payroll.provider_package.accounting.tallyprime_http.v1").first()).toBeVisible();
    await expect(page.getByText("payroll.provider_package.statutory.sdk_http.v1").first()).toBeVisible();
    await expect(page.getByText("payroll.provider_package.statutory.epfo_ecr_http.v1").first()).toBeVisible();
    await expect(page.getByText("tenant.bank.live-sdk.package.v1").first()).toBeVisible();
    await expect(page.getByText("settings.PAYROLL_PROVIDER_PACKAGES").first()).toBeVisible();
    await expect(page.getByText("Certification fixture package").first()).toBeVisible();
    await expect(page.getByText("Artifact policy readiness").first()).toBeVisible();
    await expect(page.getByText("payroll.storage.policy.default.v1").first()).toBeVisible();
    await expect(page.getByText("payroll.storage.policy.strict-runtime.v1").first()).toBeVisible();
    await expect(page.getByText("payroll.storage.policy.disabled.v1").first()).toBeVisible();
    await expect(page.getByText("Runtime credentials, Private endpoint, KMS").first()).toBeVisible();
    await expect(page.getByText("5 verified / 0 blocked").first()).toBeVisible();
    await expect(page.getByText("0 verified / 1 blocked").first()).toBeVisible();
    await expect(page.getByText("Production pack").first()).toBeVisible();
    await expect(page.getByText("Bank payout").first()).toBeVisible();
    await expect(page.getByText("Accounting journal").first()).toBeVisible();
    await expect(page.getByText("Statutory filing").first()).toBeVisible();
    await expect(page.getByText("HTTP JSON").first()).toBeVisible();
    await expect(page.getByText("payroll.provider_schema_mapping_pack.comparison.v1").first()).toBeVisible();
    await expect(page.getByText("0 changed / 17 added / 0 removed").first()).toBeVisible();
    await expect(page.getByText("bank.file_profile_ref").first()).toBeVisible();
    await expect(page.getByText("payment.employee_rows[0].employee.code").first()).toBeVisible();
    await expect(page.getByText("payroll.provider_mapping.bank.bank_advice.default.v1").first()).toBeVisible();
    await expect(page.getByText("razorpayx.bank_advice.payload.v2").first()).toBeVisible();
    await expect(page.getByText("Provider sandbox v2 schema trial.").first()).toBeVisible();
    await expect(page.getByRole("button", { name: "Clone" }).first()).toBeVisible();
    await expect(page.getByRole("button", { name: "Activate" }).first()).toBeVisible();
    await expect(page.getByRole("button", { name: "Export" }).first()).toBeVisible();
    await expect(page.getByRole("button", { name: "Archive" }).first()).toBeVisible();
    await page.getByRole("button", { name: "Edit rules" }).first().click();
    await expect(page.getByRole("dialog", { name: /rule builder/ })).toBeVisible();
    await expect(page.getByRole("heading", { name: "Source to provider payload" })).toBeVisible();
    await expect(page.getByRole("heading", { name: "Provider payload gates" })).toBeVisible();
    await expect(page.getByLabel("Target schema")).toHaveValue("razorpayx.bank_advice.payload.v2");
    await expect(page.getByLabel("Enforcement")).toHaveValue("strict");
    await expect(page.getByLabel("Source path").first()).toHaveValue("provider_ref");
    await expect(page.getByLabel("Target path").first()).toHaveValue("provider.provider_ref");
    await expect(page.locator(".payroll-rule-builder-advanced-summary", { hasText: "Expand Rows" })).toBeVisible();
    await expect(page.locator(".payroll-rule-builder-advanced-summary", { hasText: "Group Rows" })).toBeVisible();
    await expect(page.locator(".payroll-rule-builder-advanced-summary", { hasText: "4 row mappings" })).toBeVisible();
    await expect(page.locator(".payroll-rule-builder-advanced-summary", { hasText: "2 aggregates" })).toBeVisible();
    await page.getByRole("button", { name: "Run preview" }).click();
    await expect(page.getByText("Preview completed").first()).toBeVisible();
    await expect(page.getByText("Comparison").first()).toBeVisible();
    await expect(page.getByText("Diffs").first()).toBeVisible();
    await expect(page.getByLabel("Mapped provider payload")).toContainText("payment");
    await expect(page.getByLabel("Mapped provider payload")).toContainText("employee_rows");
    await expect(page.getByLabel("Mapped provider payload")).toContainText("cost_center_groups");
    await expect(page.getByLabel("Mapped provider payload")).toContainText("125000.25");
    await expect(page.getByRole("button", { name: "Save rules" })).toBeVisible();
    await page.getByRole("button", { name: "Close", exact: true }).click();
    await expect(page.getByText("payroll.provider_contract.bank.sandbox_adapter.v1").first()).toBeVisible();
    await expect(page.getByText("Latest request").first()).toBeVisible();
    await expect(page.getByText("Latest result").first()).toBeVisible();
    await expect(page.getByText("bank_advice_submission").first()).toBeVisible();
    await expect(page.getByText("payroll.provider_connection.bank.certification_scenarios.v1").first()).toBeVisible();
    await expect(page.getByText("payroll.provider.bank.sandbox.v1").first()).toBeVisible();
    await expect(page.getByText("payroll.provider_adapter.bank.sandbox.v1").first()).toBeVisible();
    await expect(page.getByText("bank-sandbox-credential").first()).toBeVisible();
    await expect(page.getByText("bank.credentials.sandbox.v1").first()).toBeVisible();
    await expect(page.getByText("bank.sftp.callback.hmac.v1").first()).toBeVisible();
    await expect(page.getByText("No raw secrets").first()).toBeVisible();

    await page.getByRole("link", { name: /Clear statutory sandbox/ }).first().click();
    await expect(page).toHaveURL(/connectionId=pay-provider-clear-statutory/);
    await expect(page.getByRole("heading", { name: "Clear statutory sandbox" }).first()).toBeVisible();
    await expect(page.getByText("clear-statutory.portal.v1").first()).toBeVisible();
    await expect(page.getByText("payroll.provider_adapter.statutory.sandbox.v1").first()).toBeVisible();
    await expect(page.getByText("clear-statutory-sandbox-credential").first()).toBeVisible();
    await expect(page.getByText("clear-statutory.credentials.sandbox.v1").first()).toBeVisible();
    await expect(page.getByText("clear-statutory.callback.hmac.v1").first()).toBeVisible();
    await expect(page.getByText("clear-statutory.pt.challan.receipt.v1").first()).toBeVisible();
    await expect(page.getByText("certification_passed").first()).toBeVisible();
    await expect(page.getByText("statutory_challan_receipt").first()).toBeVisible();
    await expect(page.getByText("statutory_callback_replay_guard").first()).toBeVisible();
    await expect(page.getByText("Pending").first()).toBeVisible();

    await expectNoHorizontalOverflow(page);
  });
});
